### ISSUE TITLE
Add IR op metadata tags in json

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#104]
Initial Metadata:

- StoreMemory
  - Stores to memory. Ensures that even if the op doesn't generate output, that it can't be DCE'd
- Volatile
  - Similar to StoreMemory. Even if it doesn't write memory, this is a volatile op that shouldn't be DCE'd

Architecture specific select of metadata
- ClobbersFlags
  - Clobbers host side flags, so if FLAG register class is used, must be spilled around this op
- NecessaryTemps
  - Number of temp registers this IR op needs to work. Will allocate a register that its live range starts at this op and then ends at the same op
- PhysicalRegisters - (We need both dest physical colouring and argument physical colouring)
  - If this op needs specific physical registers then this is an RA constraint that enforces those registers to be allocated

**Comment by alyssarosenzweig** [comment]
We do more or less this, closing
