### ISSUE TITLE
Need help compiling for Manjaro ARM

### ISSUE THREAD

**Issue by NonstickAtom785** [FEX-Emu/FEX#1109]
I'm new to the whole chroot idea. I see that we have to mount a `rootfs` for x86_64. I have installed qemu and even debootstrap for installing the chroot. My issue is what comes after that. I don't know how to set up the chroot to be piped through FEX. Can someone push me in the right direction?

Edit: I also got as far as to try to actually chroot into the rootfs. But I should have known that wasn't going to work. Incompatible binary types.

![image](https://user-images.githubusercontent.com/36454623/122991140-528e8c80-d36a-11eb-826c-3a145e8051bf.png)
This is also really vague. I don't understand the exact requirements for this to run on an Arch based system. Seems simple enough for debian though.

I am also getting similar issues to the ones in #997

**Comment by Sonicadvance1** [comment]
This github wiki page is a bit out of date for how to set up the x86-64 rootfs. (I'll delete it after this)
The wiki page on our website is much newer and has more information.
https://wiki.fex-emu.org/index.php/Development:Setting_up_RootFS

For a rough guide as to what is wrong. You need to install qemu's binfmt_misc setup on your host AND also copy the qemu-x86_64-static file over to the rootfs.
This will allow qemu to execute the x86-64 binaries inside of the rootfs so you can set things up.

**Comment by NonstickAtom785** [comment]
Hm. So mainly I should be following these steps?
![image](https://user-images.githubusercontent.com/36454623/123047121-88f7f600-d3c2-11eb-97a0-d81e5e542108.png)
Won't be able to build atm, but in the morning I'll look into building it again.(And possibly even making a better build script for arch linux arm >.<

**Comment by Sonicadvance1** [comment]
Yes, those are the steps you should be following to build the rootfs from an ARM device.

**Comment by Sonicadvance1** [comment]
Closing from non-activity. If this is still a concern, reopen or contact us on our official Discord at https://discord.gg/fexemu
