### ISSUE TITLE
Support static-pie

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1114]
We can nearly support static-pie at this point.
It's just a case of setting up cmake to play nice and fix the couple dlopen things that fex still needs.
Once we do support it then we can end up working in chroot environments. Which would be an interesting proposition.

**Comment by Sonicadvance1** [comment]
Turns out that glibc crashes with static-pie becuase of R_*_IRELATIVE relocations being broken to some extent.
http://maskray.me/blog/2020-12-19-lld-and-gnu-linker-incompatibilities Has some more information.

`nsz has a glibc patch that moves the self-relocation later so everything is set up for ifunc resolvers.`
No idea if this patch has made it upstream or where to find it.

**Comment by Sonicadvance1** [comment]
https://sourceware.org/pipermail/libc-alpha/2021-January/121752.html
Some more information here.

**Comment by Sonicadvance1** [comment]
I have confirmed locally that the static-pie IRELATIVE fixes patch[1] resolves our issues with FEX crashing when compiled with static pie.
This patch hasn't been pushed by anyone as far as I can tell, so the chance of it making 2.34 is pretty much none.

[1] https://sourceware.org/git/?p=glibc.git;a=commit;h=c67127a88540f6de4b92370158b5da61bec23f4f

**Comment by skmp** [comment]
Ouch

**Comment by Sonicadvance1** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=28066
Bug report opened.
