### ISSUE TITLE
Syscall Unit tests

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#116]
We need unit tests for these syscalls to make sure we don't break them.

**Comment by skmp** [comment]
I compiled posixtest and pushed the bins + a simple runner script >> https://github.com/FEX-Emu/fex-posixtest-bins

Early comments
- FEX doesn't propagate the exit code, so there's no simple way to wrap things up
- FEX pollutes the console output -- is there some `--silent` mode?
- FEX locks up after a few tests

Initial plan
- [ ] Fixup FEX so the simplistic runner works
- [ ] Hook up into CI
- [ ] Somehow interpret/visualize the data vs a golden "native" run of the tests

Further work
- [ ] Use a proper runner that scales across all threads. posixtest uses make for this
- [ ] Generate some kind of reports and have a webui to navigate them

Much further work
- [ ] Fixup FEX so we can run the original test suite just by doing ${FEX}make, have it launch gcc and build the tests, then have make run the tests just like posixtest would work natively

**Comment by skmp** [comment]
TODO: exit code -> exit/exitgroup -> store near ExitReason, return if no FEX error
TODO: Elfloader -> logman -> printf, --silent -s

**Comment by skmp** [comment]
This is done
