### ISSUE TITLE
Install to /usr/local

### ISSUE THREAD

**Issue by Serentty** [FEX-Emu/FEX#1169]
When I install to /usr/local, I get issues registering the binfmt handler. It seems that the path of /usr is hardcoded there. I'm a bit uncomfortable installing all of the binaries directly into /usr/bin, especially when there isn't even an uninstaller.

**Comment by Sonicadvance1** [comment]
Oops. This is a regression. Thanks for bringing it up. I'll make sure to fix it soon.
As a workaround you can change the path in the following files before install.
https://github.com/FEX-Emu/FEX/blob/main/Data/binfmts/FEX-x86
https://github.com/FEX-Emu/FEX/blob/main/Data/binfmts/FEX-x86_64
