### ISSUE TITLE
Golang needs VDSO and/or vsyscall

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#117]
Golang has a bit of assembly for using vdso or vsyscall for gettimeofday.
We don't currently support either of these.
This is necessary if we want to run any golang application.

**Comment by Sonicadvance1** [comment]
Needs documentation to how these are laid out.
@skmp can do I hope?

**Comment by skmp** [comment]
A bit of research on this:

Go assumes that if there's no VDSO available, vsyscall is. vsyscall seems disabled in recent x64 kernels.

quote "On amd64, when VDSO is not available, we fallback to the fixed
mapped helpers function for gettimeofday (at 0xffffffffff600000)," (https://github.com/golang/go/issues/8200). 

A recent Go patch fixes this, and fallbacks to doing normal syscalls when neither vsyscall nor vdso are available (https://github.com/golang/go/pull/41681).

Implementing vsyscall is not trivial, as it requires code mapped into the kernel, at a fixed location. VDSO seems more plausible, if we provide a custom VDSO object, and as the VDSO address is dynamic.

**Comment by Sonicadvance1** [comment]
32bit programs need this more

**Comment by Sonicadvance1** [comment]
Cities Skylines hardcodes VDSO usage at `uint64_t runtime.vdsoGettimeofdaySym = 0xffffffffff600000`

**Comment by Sonicadvance1** [comment]
Stellaris also hardcodes VDSO usage like Cities Skylines.

**Comment by Sonicadvance1** [comment]
Same with Imperator: Rome

**Comment by Sonicadvance1** [comment]
We support both of these now.
