### ISSUE TITLE
Syscall emulation has incorrect global mutex

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#12]
There is a scoped mutex at the top of the syscall handling function.
This is incorrect and causes the application to stall once threading kicks in.
Should be removed and only have a mutex on things that actually need it.
Can be done alongside syscall cleanup.

I think skmp wanted to have a go at this?

**Comment by skmp** [comment]
Is this still an issue?

**Comment by Sonicadvance1** [comment]
aye
