### ISSUE TITLE
Compatible with Linux4Tegra (e.g. Nintendo Switch, Nvidia Shield)?

### ISSUE THREAD

**Issue by Star-X555** [FEX-Emu/FEX#1206]
Asking as this would effectively solve the issue of Steam Remote Play being nearly impossible to get working adequately on the Switch with rail-based joycons (since there isn't a native version of Steam Link for ARM Linux, and Android still has incredibly buggy rail joycon support that stops working half the time).

**Comment by Sonicadvance1** [comment]
Should just work fine with the caveats about ARMv8.0 and the slowness of Cortex-A57.
