### ISSUE TITLE
Implement BMI1 and BMI2

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1261]
These map quite well to AArch64. We should probably just support this.

**Comment by lioncash** [comment]
BMI1's BEXTR is implemented as of https://github.com/FEX-Emu/FEX/pull/1337

**Comment by lioncash** [comment]
As of https://github.com/FEX-Emu/FEX/pull/1353 (implements BLSR and BLSMSK) BMI1 support is complete.

(also forgot to update with https://github.com/FEX-Emu/FEX/pull/1344 which implements BLSI)

Now onwards to BMI2

**Comment by lioncash** [comment]
SARX, SHLX, and SHRX from BMI2 are implemented in https://github.com/FEX-Emu/FEX/pull/1354

**Comment by lioncash** [comment]
BMI2's RORX is now implemented as of #1361

**Comment by lioncash** [comment]
BMI2's BZHI is now implemented as of https://github.com/FEX-Emu/FEX/pull/1375

**Comment by lioncash** [comment]
BMI2's PEXT is supported as of https://github.com/FEX-Emu/FEX/pull/1440

**Comment by lioncash** [comment]
BMI2's PDEP is supported as of https://github.com/FEX-Emu/FEX/pull/1445 which completes this issue

**Comment by lioncash** [comment]
Closing, since BMI1 and BMI2 are now implemented
