### ISSUE TITLE
Incorrect orbital familiars movement in The Binding of Isaac: Rebirth

### ISSUE THREAD

**Issue by neobrain** [FEX-Emu/FEX#1374]
Orbital familiars are supposed to spin in a circular motion around the main character. In FEX however they bounce around in a semi-circle, changing movement direction each time they have moved by 180°. This can easily be reproduced within few seconds in challenge 6 ("Solar System"), where the main character starts with a number of orbital familiars that each have this problem.

This also affects enemy groups that normally arrange in circles, such as the pink ring flies, which arrange in a semi-circle in FEX instead.

**Comment by Sonicadvance1** [comment]
This will likely also relate to why Source Engine games don't let you rotate the camera a full 360 degrees.

**Comment by Sonicadvance1** [comment]
https://cdn.discordapp.com/attachments/765304672579092511/910807192419069962/Binding-2021-11-18_00.20.43.mp4
A video showing the flies around Isaac not doing a full 360 degree movement.
Both the black flies and blue flies exhibit the problem. For some reason the red fly is unaffected.

**Comment by skmp** [comment]
Is there a save file I can use to get directly to challenge 6 @neobrain ?

**Comment by skmp** [comment]
Reproduced on leo (AWS/g2) though at 0.5fps.

Attached is the save file I used. To repro, one must start a new game, then exit (for the save folders to be created) then to copy the .dat file to `~/.local/share/Steam/userdata/<steam_uid>/250900/remote/`

[persistentgamedata1.zip](https://github.com/FEX-Emu/FEX/files/7718788/persistentgamedata1.zip)

The two black flies should be rotating in the same direction, with a phase difference of 180 degrees, doing a 360 degree rotation. Instead they rotate ~ 45 degrees each, switching between towards each other to oposite each other.

The red and blue flies should be rotating opposite to each other, but it looks like the blue one switches rotation direciton.

Compared against https://www.youtube.com/watch?v=0DGzXoHf5Ec&ab_channel=NintenU

Will try to repro on mangie (x86-64, amd graphics) to see performance and behavior on x86 host

**Comment by skmp** [comment]
Modding community could be helpful

**Comment by skmp** [comment]
Setup renderdoc and spent a substantial amount of time trying to get it working, looks like I'll have to repeat from an x86-64 host.

**Comment by Sonicadvance1** [comment]
Found the problem. It's FPREM!
