### ISSUE TITLE
FEX-Emu not working anymore inside Termux PRoot container

### ISSUE THREAD

**Issue by AarizYT** [FEX-Emu/FEX#1389]
Distro:- Arch Linux ARM64 (running on Termux PRoot container)

Error:-
`[ERROR] [Unsupported] FEX mapped to lower 32bits! Exiting!`

**Comment by Sonicadvance1** [comment]
Nothing has changed in this regard for quite a few months.
This usually happens if you manage to compile FEX without pie/static-pie support.
You'll need to figure out why FEX isn't getting compiled as a pie executable.

**Comment by AarizYT** [comment]
So I tested around a little and compiled it a few more times and I noticed that everything except FEXLoader, FEXInterpreter, IRLoader and UnitTestGenerator works. FEXLoader and FEXInterpreter both get the lower 32 bit map error while the IRLoader and UnitTestGenerator crashes with Segmentation fault. I also used hardening-check to check if the executables were PIE executable and it seems that they are. Is there anything else I can provide to help fix this problem?

**Comment by Sonicadvance1** [comment]
Please provide the output of the following commands:
`file ./Bin/FEXLoader`
`readelf -h ./Bin/FEXLoader`
`ldd ./Bin/FEXLoader`

**Comment by AarizYT** [comment]
Here's the output:-
[Log.txt](https://github.com/FEX-Emu/FEX/files/7611325/Log.txt)

**Comment by Sonicadvance1** [comment]
I updated the main branch so FEX prints more debug data about the memory map on this failure case.
Rebuild, run and provide that output.
Looks like the dynamic linker in Termux might be messing with FEX.

**Comment by AarizYT** [comment]
Here's the output for FEXLoader:- 
[Log2.txt](https://github.com/FEX-Emu/FEX/files/7611404/Log2.txt)
And for FEXInterpreter:-
[Log3.txt](https://github.com/FEX-Emu/FEX/files/7611405/Log3.txt)

**Comment by Sonicadvance1** [comment]
Looks like whatever `/data/data/com.termux/files/usr/libexec/proot/loader` this application is, steals a page of memory in the lower 32-bits.
This is causing our check to get upset and early exit.
Definitely not entirely fatal unless an application is set to load at that address.
We could probably downgrade this error in to a non-fatal warning since a single missing page won't be that big of a problem.

**Comment by Sonicadvance1** [comment]
I've updated the main branch so that this error is no longer fatal. FEXLoader/FEXInterpreter will still print the message, but will try to continue afterwards.

**Comment by AarizYT** [comment]
Thanks, it's working now.
