### ISSUE TITLE
FEX-EMU infrastructure

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#145]
We have
- [fex-emu.org](fex-emu.org)
- [Google Calendar](https://calendar.google.com/calendar?cid=MWtyZTFtYzZzZnJwYm4zM2YyajQxdHFrdWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)
- [Google Drive Share (RO)](https://drive.google.com/open?id=1tWQbqYd4lJH54VVnMWaSAoEyP_ac0_Sa)
- email forwards for skmp, phire, hdkr @fex-emu.org
- [chat.fex-emu.org redirect](https://chat.fex-emu.org)

We need
- Bot that auto merges PRs approved / made by @FEX-Emu/maintainers 
- A non hello world website (See https://github.com/FEX-Emu/fex-emu.org/issues/1)

In the future
- Register our trademark/namemark (@skmp can look into pricing in greece for worldwide, so we have an idea of the costs involved)
- a formal entity to represent us (@phire suggested looking into the NZ options to do this, so we have an idea of the costs and complexity involved)

**Comment by skmp** [comment]
I also think that
- Our weekly meeting minutes should be published
- We should do a monthly progress report

**Comment by skmp** [comment]
As well as
- Irc bridge to #irc in the Fex discord server

**Comment by skmp** [comment]
@Sonicadvance1 @phire any further ideas you might have?

**Comment by alyssarosenzweig** [comment]
Mix of resolved / no longer relevant / not actionable, closing
