### ISSUE TITLE
Convert all string formatting to {fmt}

### ISSUE THREAD

**Issue by phire** [FEX-Emu/FEX#146]
Rather than `printf` and `cout` everywhere, [{fmt}](https://fmt.dev/latest/index.html) is the future

It's an implementation of std::format that works in versions of c++ before c++20. By standardising on {fmt} now, we can easily switch to `std::format` later.

**Comment by neobrain** [comment]
Is there much left to do here (cc @lioncash)?

**Comment by lioncash** [comment]
I think for the most part, this can be considered resolved
