### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by AarizYT** [FEX-Emu/FEX#1470]
Environment:- Arch Linux ARM64 (Termux PRoot container)

Error log:-
[Log.txt](https://github.com/FEX-Emu/FEX/files/7779418/Log.txt)

**Comment by Sonicadvance1** [comment]
I just noticed this issue yesterday with a "strange" build environment as well. Not quite sure why it is happening yet.

**Comment by Azkali** [comment]
I can report the same error happening when building main on 4.9.140 kernel, fedora 35, Tegra X1.

**Comment by RuggedPineapple** [comment]
can also confirm, on a pi 4 running ubuntu 21.10

**Comment by Sonicadvance1** [comment]
As a sanity check, we use python3 to generate this file. Is python3 installed on the host system?

**Comment by AarizYT** [comment]
I have python3 installed. 
`# python --version
Python 3.9.9`

**Comment by Sonicadvance1** [comment]
More specifically, FEX's cmake file calls in to the `python3` executable directly rather than just using `python`. Hopefully they both exist?

**Comment by AarizYT** [comment]
Yeah `python3` is also there.
`python3 --version`
`Python 3.9.9`

**Comment by Sonicadvance1** [comment]
Dang. Thanks for the confirmation.

**Comment by jerbmega** [comment]
I can also reproduce on a Xavier AGX running L4T Ubuntu unofficially updated to 20.04. Python3 exists and reports as 3.8.10.

**Comment by jerbmega** [comment]
I performed a bisect and found the culprit is edc31fe.

**Comment by Sonicadvance1** [comment]
That narrows down the problem scope.
#1481 may resolve this build problem.

**Comment by jerbmega** [comment]
Build from main is working on my end now, thank you!

**Comment by Sonicadvance1** [comment]
Woo \o/
