### ISSUE TITLE
IR: ConstProp potentially incorrect mask

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1508]
https://github.com/FEX-Emu/FEX/blob/main/External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp#L358

This mask value is set but never used. Looks like it should be used in place of `imm` on line `auto newArg = RemoveUselessMasking(IREmit, IROp->Args[i], imm);` but needs to be investigated.

**Comment by skmp** [comment]
I'll take a look

**Comment by skmp** [comment]
The code there is definitely buggy, however as RemoveUselessMasking has been disabled it doesn't actually optimize anything.

Related: #594

The only functional parts of the optimization are
- BFE/SBFE (partially)
- VFADD/VFSUB/VFMUL/VFDIV/FCMP
- VMOV (partially)

**Comment by skmp** [comment]
I think the entire optimization pass needs a rewrite, both to work out the kinks, and to be faster
