### ISSUE TITLE
Raspberry Pi ::::: I Cant Install Any Packages After Install RootFS

### ISSUE THREAD

**Issue by cheznewa** [FEX-Emu/FEX#1528]
After Installed The RootFS The Sudo Isnt Work So No Admin Inside And No Package To Installed It!
I Try With ArchLinux, There No Networking, So, Always NOT Packages!!

On My Raspberry Pi 400
Raspberry Pi OS Bulleyes 64 Bit.

**Comment by Sonicadvance1** [comment]
1) Did you download the one of the `.sqsh` rootfs images?
2) Did you extract the rootfs with `unsquashfs`?
3) Did you run `unbreak_chroot.sh` inside of that rootfs?
4) If you did this. Then you are already running as root user in the chroot. No need for sudo.

Additional: https://wiki.fex-emu.org/index.php/Development:Setting_up_RootFS#If_you_want_to_install_packages_in_the_squashfs
This steps may help you.

**Comment by cheznewa** [comment]
1 And 2 Yes But Not The 3 Where The Script unbreak_chroot.sh ?

**Comment by Sonicadvance1** [comment]
The `unbreak_chroot.sh` script is in the root of the rootfs that FEX provides.
eg:
```bash
~/.fex-emu/RootFS/Ubuntu_21_10$ ls -lah
total 36K
drwxr-xr-x  7 ryanh ryanh 4.0K Jan 14 16:40 .
drwxrwxr-x  4 ryanh ryanh 4.0K Jan 13 23:05 ..
lrwxrwxrwx  1 ryanh ryanh    7 Oct 11 10:19 bin -> usr/bin
-rwxr-xr-x  1 ryanh ryanh 2.0K Nov 20 07:52 break_chroot.sh
drwxrwxr-x 11 ryanh ryanh 4.0K Jan 14 16:40 chroot
drwxr-xr-x 96 ryanh ryanh 4.0K Jan 14 16:40 etc
lrwxrwxrwx  1 ryanh ryanh    7 Oct 11 10:19 lib -> usr/lib
lrwxrwxrwx  1 ryanh ryanh    9 Oct 11 10:19 lib32 -> usr/lib32
lrwxrwxrwx  1 ryanh ryanh    9 Oct 11 10:19 lib64 -> usr/lib64
lrwxrwxrwx  1 ryanh ryanh   10 Oct 11 10:19 libx32 -> usr/libx32
drwxr-xr-x 10 ryanh ryanh 4.0K Nov 20 07:58 run
lrwxrwxrwx  1 ryanh ryanh    8 Oct 11 10:19 sbin -> usr/sbin
-rwxr-xr-x  1 ryanh ryanh 2.2K Nov 20 07:52 unbreak_chroot.sh
drwxr-xr-x 14 ryanh ryanh 4.0K Nov 20 08:05 usr
drwxr-xr-x 12 ryanh ryanh 4.0K Nov 20 07:58 var
```

**Comment by cheznewa** [comment]
I Cant Get Here ::::
* When Leave And Inside Chroot And Root, After My Username Is None "I have no name!", And Not Work Sudo :(

**Comment by Sonicadvance1** [comment]
`I have no name!` is normal and non-fatal.
The user in the chroot will still be root. Don't use sudo at that point.

**Comment by cheznewa** [comment]
I Follow The Doc But Same If I Do Without Sudo, He Say ::::: "Access Denied"

**Comment by Sonicadvance1** [comment]
I don't have a solution for that.
Could be an issue with ArchLinux trying to chroot in to an Ubuntu RootFS.
I don't have an ArchLinuxARM install to try and reproduce.

**Comment by cheznewa** [comment]
OK "Merci Quand Même" I Return To Exagear...
END.
