### ISSUE TITLE
FPREM/FPREM1: Support rounding mode differences between these instructions

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1538]
FPREM1 follows IEEE remainder while FPREM does not.
We should support the differences between these two instructions. Currently they map to the same instruction implementation.

In particular: FPREM always truncates the quotient towards zero while FPREM1 rounds towards nearest.

**Comment by Sonicadvance1** [comment]
derpy github auto close.

**Comment by alyssarosenzweig** [comment]
Fixed
