### ISSUE TITLE
No uninstall with ninja

### ISSUE THREAD

**Issue by Raezroth** [FEX-Emu/FEX#1592]
Wondering is there plans for a way to uninstall FEX from you system

**Comment by Sonicadvance1** [comment]
This falls under the typical problem that users shouldn't be doing `ninja install` and instead defer to package managers.

This is why we provide an Ubuntu PPA that we manage.
We are looking to expand this to Arch packages and managing the termux packages ourselves.
If you are using a linux distro that isn't one of those three then we can look at adding support for that as well.

As for actually adding an uninstall target, We can look at adding it but it isn't very high priority.
cmake generates an install manifest that you can use to mostly uninstall things
`cat install_manifest.txt | sudo xargs rm`

**Comment by skmp** [comment]
```
# make uninstall
add_custom_target("uninstall" COMMENT "Uninstall installed files")
add_custom_command(
    TARGET "uninstall"
    POST_BUILD
    COMMENT "Uninstall files with install_manifest.txt"
    COMMAND xargs rm -vf < install_manifest.txt || echo Nothing in
            install_manifest.txt to be uninstalled!
)
```
?

This would be useful for me during development too

**Comment by Sonicadvance1** [comment]
Looks like that would work.
