### ISSUE TITLE
How to compile in Termux (no proot)

### ISSUE THREAD

**Issue by sukualam** [FEX-Emu/FEX#1642]
Im trying to compile latest fex-emu on termux , but failed. 

Im not in proot, so it still on android.

Is i need to proot/chroot first?

![Screenshot_20220330-090345_Trebuchet](https://user-images.githubusercontent.com/11465849/160735959-c44320c9-3eb2-4f8d-8a9b-af143c7e8014.png)

**Comment by Sonicadvance1** [comment]
Should be an easy enough fix. Investigating.

**Comment by sukualam** [comment]
I use this tutorial https://wiki.fex-emu.org/index.php/Development:Setting_up_FEX

I run the commands directly to the termux.

**Comment by sukualam** [comment]
Am i missing some dependency in termux?

**Comment by Sonicadvance1** [comment]
No. This is just the build being broken in Termux. We don't have CI for the platform so this happens.

**Comment by sukualam** [comment]
so i need to proot ?

**Comment by Sonicadvance1** [comment]
It needs the code to be fixed. Or for you to use the termux FEX-emu provided package.

**Comment by sukualam** [comment]
i realized that fex is available on termux repo
