### ISSUE TITLE
FEXLoader fails to run itself in ENABLE_X86_HOST_DEBUG

### ISSUE THREAD

**Issue by juulvanderspek** [FEX-Emu/FEX#1646]
Not sure if this is an important case, but hit it when I was playing around with FEX:

$  ~/FEX/Build/Bin/FEXLoader -- ~/FEX/Build/Bin/FEXLoader /usr/bin/zip
Illegal instruction (core dumped)

 
 Build command:
 CC=clang CXX=clang++ cmake  -DENABLE_X86_HOST_DEBUG=True -DENABLE_LLD=True -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DENABLE_LTO=True -DBUILD_TESTS=False -G Ninja ..

$ uname -a
Linux jvanderspek-lap 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Sonicadvance1** [comment]
This is because when you're building on an x86-64 host, it is building with `-march=native`, so you're likely to get AVX instructions emitted. FEX doesn't support executing AVX currently.
This is also an unsupported use case.
