### ISSUE TITLE
RA pass should use less memory

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1655]
The register allocation pass uses a significant amount of memory .
This should be setup to use the thread pool allocator so threads can eventually relinquish ownership of their buffers.
This isn't a simple task because we are relying on some destructors to run at some points.

The biggest contributor to memory usage is `std::vector<RegisterNode> Nodes{};` inside of RegisterGraph since we always allocate that to 8192 nodes per thread by default. Which makes it be 4MB per thread, expanding beyond that if the node count isn't enough.

The second largest usage there is the RegisterGraph itself, which I believe is mostly from the RegisterSet but that would need to be checked on.

These are all allocated without mmap, so it adds up quickly how much memory it uses. Especially when running something like Steam with a bunch of processes and threads.

**Comment by Sonicadvance1** [comment]
![Image_2022-04-23_10-38-07](https://user-images.githubusercontent.com/1018829/164925949-27023c85-0279-41a0-babb-193c2f84f77e.png)
As seen in this heaptrack output, you can see that there is a significant spike of memory usage once the GL context starts up and mesa spins up something like 30 worker threads.
In a longer running application, using the thread pool allocator would allow this to peak memory usage to quickly go away since a lot of threads end up sleeping.

**Comment by skmp** [comment]
Closing in favor of #1910
