### ISSUE TITLE
MWAIT/MWAITX with WFE/WFET?

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1660]
These can be implemented using the global exclusive monitor.

WFET is quite new with ARMv8.7, WFE has been around for a while.

**Comment by Sonicadvance1** [comment]
Nevermind, WFE/WFET isn't actually a great choice here because you'll get spurious wakeups unrelated to the monitor address and you can't actually tell which event woke up the WFE/WFET.

Tested with a simple case that all it does is do an exclusive load of a cacheline and wfe and measures the time until wakeup.
Every 42 nanoseconds my unit test would spuriously wakeup even without an exclusive monitor clear.
Purely because WFE can be woken up by many different things.

**Comment by skmp** [comment]
That's still a few orders of magnitude better than busy wait

**Comment by Sonicadvance1** [comment]
Looks like MWAIT and MWAITX can both cause spurious wake ups. Need to do some hardware testing to see what its behaviour is like.
```
There is no indication after exiting MWAITX of why the processor exited or if the timer expired. It is
up to software to check whether the awaiting store has occurred, and if not, determining how much
time has elapsed if it wants to re-establish the MONITORX with a new timer value
```

**Comment by Sonicadvance1** [comment]
Also side note here, MWAIT itself is only available in CPL-0, where MWAITX is available in CPL-3.
But there are some other similar extensions (UWAIT I think it is called?)

**Comment by Sonicadvance1** [comment]
Tested MWAITX. This has a spurious wakup every ~399'0000 nanoseconds on my 2990WX test platform.
Quite a significant difference compared to 42ns on M1 and 52ns on Snapdragon 888.

**Comment by Sonicadvance1** [comment]
Some more minor investigation in to this.
WFE/WFET isn't a good fit here since the number of wakeup events tied to what WFE waits for is significantly more than MWAIT/MWAITX.
We can never get a longer sleep than 10Khz even because the architecture event timer is configured to that amount.
Of course there are other events that WFE also wakes up for.

If we wanted to emulate this then we would architecturally need an instruction that like WFE but with an event mask to explicitly wait on exclusive monitor only (plus interrupts and some other required spurious wakeups).

**Comment by Sonicadvance1** [comment]
Not a good fit unless ARM decides to implement something similar without such aggressive spurious wake-ups.
Can revisit this if an application really wants busy-loops with some power savings.
