### ISSUE TITLE
Host deferred signals

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#1715]
This is an alternative way for us to avoid signal reentrancy amplification issues, vs blocking signals.

Split from #1666,

> (a) Is easy to do by adding a "is signal pending" check before returns to the JIT (syscalls, compile code, other non-thunks). This can be easily done either in the dispatcher/jit side, or the C++ side. The only complication is automatically restarted system calls. It has near zero overhead, and doesn't suffer from execution 'overshot' of guest deferred signal, just delayed signal delivery. This will largely resolve signal safety issues.

**Comment by neobrain** [comment]
I *think* this is implemented nowadays. Hard to tell given the scarce description.

**Comment by Sonicadvance1** [comment]
https://github.com/FEX-Emu/FEX/blob/main/docs/DeferredSignals.md
Implemented for outside of JIT facing signals which was the main this this cared about.
