### ISSUE TITLE
Reclaim SRA registers when running 32-bit x86 applications

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1717]
Currently FEX hardcodes GPR and FPR static register allocation to be 16 registers apiece.
This is wasteful on 32-bit x86 since those applications only have access to 8 GPRs and 8 FPRs (plus MMX but we don't SRA though).

If we are running a 32-bit application we should change our register allocator so it reclaims those remaining 8+8 registers as temporaries. This should give 32-bit applications a minor performance boost but nothing significant.

**Comment by skmp** [comment]
There's a ticket for that (#609) as follow up from the SRA PR, as well as several other optimisation followups (#608 #607  #611 #610)

**Comment by skmp** [comment]
Closing in favor of #1910
