### ISSUE TITLE
FEXServer breaks unbreak_chroot.sh

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#1821]
skmp@ornio:~/.fex-emu/RootFS/Ubuntu_21_04$ ./unbreak_chroot.sh 
Moving rootfs files back to original location
Moving rootfs folders back to original location
Moving rootfs apt folders back to original location
Changing rootfs permissions on /tmp
Mounting rootfs paths
Mounting aarch64 paths
Chrooting into container
!!! Make sure to execute break_chroot.sh after leaving !!!
[ERROR] Couldn't execute: FEXServer
[ERROR] This means the squashFS rootfs won't be mounted.
[ERROR] Expect errors!
[ERROR] FEXServerClient: Failure to setup client

**Comment by Sonicadvance1** [comment]
Make sure your unbreak_chroot.sh script is the latest from https://github.com/FEX-Emu/RootFS/blob/main/unbreak_chroot.sh
Rootfs will be updated at release time.

**Comment by skmp** [comment]
Ah, no, it was the one that shipped with the image
