### ISSUE TITLE
Vulkan thunking support with zink

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1838]
While this isn't an ideal situation that an x86/x86-64 Zink is communicating with an AArch64 vulkan thunk, this should be a case we support.
Currently this crashes our Vulkan thunks

```
vkGetInstanceProcAddr: Couldn't find Guest symbol: 'vkGetInstanceProcAddr'
```

It searches for a bunch of vulkan symbols that don't exist so it definitely performs a bit odd compared to regular applications.

**Comment by neobrain** [comment]
This seems to have been working for a while. Support for zink on Wayland was implemented in https://github.com/FEX-Emu/FEX/pull/3126, and from quick testing it looks like Super Meat Boy runs fine on X11+zink too.
