### ISSUE TITLE
docker build-FindSDL2.cmake

### ISSUE THREAD

**Issue by gxiaob** [FEX-Emu/FEX#1853]
The error information is as follows，how to solve it？Thangk you！

CMake Error at Source/Tools/FEXConfig/CMakeLists.txt:7 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by Sonicadvance1** [comment]
The docker build file isn't really actively maintained. It's likely missing `libsdl2-dev` from our build dependencies on the wiki https://wiki.fex-emu.org/index.php/Development:Setting_up_FEX#Build_dependencies

**Comment by gxiaob** [comment]
Thank you！Could you help to maintain the dockerfile？So that it can adapt to different server。Now new problem comes out。How to solver it？The error information is as follows，
FAILED: Bin/FEXLoader 
: && /usr/bin/clang++-10  -O3 -DNDEBUG -fomit-frame-pointer -flto=thin  -Xlinker --gc-sections -Xlinker --strip-all -Xlinker --as-needed -fPIE -pie Source/Tests/CMakeFiles/FEXLoader.dir/FEXLoader.cpp.o Source/Tests/CMakeFiles/FEXLoader.dir/AOT/AOTGenerator.cpp.o  -o Bin/FEXLoader  External/FEXCore/Source/libFEXCore.a  Source/Common/libCommon.a  Source/Tests/LinuxSyscalls/libLinuxEmulation.a  -lpthread  External/fmt/libfmt.a  External/cpp-optparse/libcpp-optparse.a  External/json-maker/libjson-maker.a  External/FEXCore/Source/libFEXCore.a  External/FEXCore/Source/libFEXCore_Base.a  External/fmt/libfmt.a  External/vixl/src/libvixl.a  -ldl  External/xxhash/libxxhash.a  External/tiny-json/libtiny-json.a  -lpthread && :
/usr/bin/ld: error: Failed to link module External/FEXCore/Source/libFEXCore.a.llvm.8550070.jemalloc.c: Expected at most one ThinLTO module per bitcode file
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Sonicadvance1** [comment]
This looks like the bug of cmake enabling thinlto even though the linker doesn't support it. Can either change the cmake command to disable LTO, or switch over to using LLD as the linker.
Either `-DENABLE_LTO=False` or -DENABLE_LLD=True`

**Comment by gxiaob** [comment]
Thank you！Now the docker runs well ，my purpose is to run a x86 exe within arm server，now I have move exe into docker of flex，but i do not know how to use it，is there any exmaple？

**Comment by gxiaob** [comment]
Is it like this ?I get some error.The pagesize should 4k？
![image](https://user-images.githubusercontent.com/2863136/179912095-7fc85b90-7dc5-4998-b884-67be12ff0154.png)

**Comment by gxiaob** [comment]
Thank you！

**Comment by neobrain** [comment]
Looks like everything is done here. If you have any further specific issues, please open a new report.
