### ISSUE TITLE
48-bit VA breaks proton 7.0

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1933]
Just noticed this in my testing, I wasn't running 48-bit for a while so I didn't notice this being broken.
Works with 36-bit VA but not 48-bit

**Comment by skmp** [comment]
hmm, related to #1922 ?

**Comment by Sonicadvance1** [comment]
Unrelated, 39-bit VA still works with Proton 7.0. I was testing 39-bit with proton experimental in #1922.

**Comment by skmp** [comment]
@Sonicadvance1 put this for 2212, as a 'nice to have', does that make sense to you?

**Comment by Sonicadvance1** [comment]
Fixed
