### ISSUE TITLE
Proton Crash in both experimental, 7.0-4 and other versions

### ISSUE THREAD

**Issue by PietHelzel** [FEX-Emu/FEX#1951]
When running games through Steam via Proton, the game crashes without giving any proper error message. Last message returned before exiting:

`Game process removed: AppID 322170 "/home/odin/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=322170 -- '/home/odin/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- 'home/odin/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun '/home/odin/.local/share/Steam/steamapps/common/Geometry Dash/GeometryDash.exe'", ProcID 4847`

This error message is virtually the same when running different Proton versions and different games (games tested: Geometry Dash, Arietta of Spirits, Final Fantasy 7, Sayonara Wild Hearts). Linux Native games work without issue.

Device: AYN Odin Pro
uname -a: Linux valhalla 5.18.3-odin-arm64 #5 SMP PREEMPT Wed Jul 13 14:36:06 WIB 2022 aarch64 GNU/Linux

**Comment by artdeell** [comment]
As far as I recall, Geometry Dash does not work under Proton even on native x86_64 Linux systems

**Comment by skmp** [comment]
@PietHelzel which FEX version?

**Comment by PietHelzel** [comment]
Version is FEX-2208-36-g097184c

**Comment by Sonicadvance1** [comment]
Fixed now with FEX-2211.
