### ISSUE TITLE
Project power grab

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#1965]
Hello ya all,

![Screenshot from 2022-09-01 17-02-35](https://user-images.githubusercontent.com/393266/187935806-81d7b2e5-a91e-4530-a067-a4cdd4a54537.png)

I consider this to be schemed by @Sonicadvance1, as @phire has minimal commits to the project, and hasn't been active in a very long time.

To give some context, I internally raised some issues wrt to @neobrain's conduct, then the next meeting was canceled a few hours before because @Sonicadvance1  "had to travel", then my admin rights in fex-emu.org google workspace were somehow missing, and not willing to be re-instanted, and while I was blissfully working on some other things I saw this.

Even though my access to the discord server was removed, I've kept logs of my original complaint, as well as the (several pages) of discussion that followed with @phire.

@Sonicadvance1 and @neobrain didn't participate at all for days.

In order to prevent the spreading of further misinformation, and in my defence towards https://fex-emu.com/Uncomfortable-decision/ and https://twitter.com/FEX_Emu/status/1565334640423948288, I'll be redirecting fex-emu.org to a more neutral page.

I would like to state here, I was given no time to appeal the process or advance knowledge before the public posts, which is indicative of a power grab, as I didn't have any chance to review the accusations, defend myself or bring forth evidence.
 
While fex-emu was supposed to be a collective / consensus based project, at least in discussions, in practice there had been a lack of transparency in communications and a clear internal hierarchy established, with @Sonicadvance1 not sharing information with the other "maintainers". 

I'm asking of everyone involved, to take a mediation step and try to resolve this, and to discuss everything in public, so long as we are not contractually bound not to do so, as to avoid behind the scenes scheming.

I guess I'll update this ticket with further information?

Not sure if I'm still a member of the github org, but if so I'll be removing myself as I'm clearly not welcome here.

**update**
Of course i've been removed, it's a proper power grab ;)

**update 2**
https://fex-emu.org/ now has a banner linking to this issue, and an iframe of fex-emu.com after that

**Comment by skmp** [comment]
Notice here that emails @fex-emu.org are no longer being forwarded to Google, as a temporary measure while we all process the next steps. I will setup auto bounce as soon as possible, to inform any incoming email of the situation and link them to this ticket, and will be seeking advice from cooler, more knowledge heads on how to proceed from here.


Until this incident clears up I will also be forwarding emails to their original recipients, as to minimise disruption the project’s operations further.

**Comment by skmp** [comment]
@dmiller423 offered to be a custodian, isn't that right Z?

**Comment by skmp** [comment]
@phire I see you keep intervening, even though it's not quite documented based on what merit you are a maintainer, about my screenshot I heard. 

Why don't you make the server public? That discussion was in the server.

Is it private and there were no replies because some people were ganging up on someone, so they needed to isolate them?

**Comment by phire** [comment]
Exclusion from the community includes GitHub. Air your grievances elsewhere.
