### ISSUE TITLE
Can't execute  FEXRootFSFetcher and sometimes can't compile FEX(in termux)

### ISSUE THREAD

**Issue by woshigenm** [FEX-Emu/FEX#1967]
I use  termux to execute that command

When i execute  the FEXRootFSFetcher. It can't be executed and print "terminate called after throwing an instance of 
 'std::out_of_range'  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)"
I don't know the command that why it can't be executed .
Sometimes I compile FEX，the compile program offten throw compile error. it's strange

**System information:**
 - OS: Android 12
 - terminal:termux(0.118.0)
 - CPU/SoC: MTK8100(rubens)
 - Video driver version: openGl 4.5 (Compatibility Profile) Mesa 22.1.7
 - RootFS used: Ubuntu Kinetic Kudu (development branch) aarch64
 - FEX version: FEX-2208-45-g12fee91
 - Thunks Enabled: no

**To Reproduce**
1.sudo apt install cmake make ninja-build clang libglfw3-dev libsdl2-dev libepoxy-dev g++-x86-64-linux-gnu nasm squashfuse squashfs-tools
2. git clone https://github.com/FEX-Emu/FEX.git && git submodule update --init
3. mkdir build && cd build
4.CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=True -DBUILD_TESTS=False -G Ninja ..
5. error:
CMake Error at /lib/aarch64-linux-gnu/cmake/SDL2/sdl2-config.cmake:13 (message):
     File or directory //include/SDL2 referenced by variable SDL2_INCLUDE_DIR
          does not exist !
         Call Stack (most recent call first):
         /lib/aarch64-linux-gnu/cmake/SDL2/sdl2-config.cmake:27 (set_and_check)
         Source/Tools/FEXConfig/CMakeLists.txt:7 (find_package)

6.more details of error:
      Run Build Command(s):/bin/ninja cmTC_6413d && [1/2] Building C object
      CMakeFiles/cmTC_6413d.dir/HAVE_GDB_JIT_READER_H.c.o
      FAILED: CMakeFiles/cmTC_6413d.dir/HAVE_GDB_JIT_READER_H.c.o 
      /bin/clang    -MD -MT CMakeFiles/cmTC_6413d.dir/HAVE_GDB_JIT_READER_H.c.o -MF 
     CMakeFiles/cmTC_6413d.dir/HAVE_GDB_JIT_READER_H.c.o.d -o CMakeFiles/cmTC_6413d.dir/HAVE_GDB_JIT_READER_H.c.o -c 
     /root/FEX/build/CMakeFiles/CheckIncludeFiles/HAVE_GDB_JIT_READER_H.c
    /root/FEX/build/CMakeFiles/CheckIncludeFiles/HAVE_GDB_JIT_READER_H.c:2:10: fatal error: 'gdb/jit-reader.h' file not found
    #include <gdb/jit-reader.h>
         ^~~~~~~~~~~~~~~~~~
    1 error generated.
     ninja: build stopped: subcommand failed.

     Source:
     /* */
     #include <gdb/jit-reader.h>

     int main(void)
      {
         return 0
       ;}

Please tell me what i should  do to solve the problem
The last one is your wiki website could't be visited and i can't get help in time
Have a good day

**Comment by woshigenm** [comment]
> _No description provided._

**Comment by Sonicadvance1** [comment]
FEXRootFSFetcher being broken is a known issue. Will be fixed tomorrow.
As for building under Termux, it looks like you're missing some dependencies from https://wiki.fex-emu.com/index.php/Development:Setting_up_FEX#Build_dependencies

You will also need patches from the termux package:https://github.com/termux/termux-packages/tree/master/packages/fex

**Comment by woshigenm** [comment]
> The variable SDL2_INCLUDE_DIR is null in sdl2-config.cmake ,so the FEX  couldn't be compiled
