### ISSUE TITLE
FEXLinuxTests: SIGFPE not raised in ./synchronous-signal-block.64

### ISSUE THREAD

**Issue by neobrain** [FEX-Emu/FEX#1980]
`./synchronous-signal-block.64 sfpe` and `./synchronous-signal-block.64 afpe` should print `Got 8 at address: ...` since they're triggering a SIGFPE. However, when running these tests in FEXInterpreter, that doesn't seem to be the case.

I have not ran those tests on an x86 host yet, so it's unclear if the bug is in FEX or in the test.

**Comment by Sonicadvance1** [comment]
For one thing, the test is abusing the fact that integer divide by zero on x86 results in SIGFPE.
Secondly, AArch64 divide by zero doesn't raise an exception.
Thirdly, the only ARM hardware that supports float exceptions is Apple hardware, Which we check for in HostFeatures.cpp with `SupportsFloatExceptions`, but we don't currently enable or wire up at all.

**Comment by neobrain** [comment]
Thanks, I forgot about those architecture constraints.

This is actually mentioned in the `Known_Failures` lists already, so I'm closing this issue in favor of those.
