### ISSUE TITLE
Resolve VIXL simulator narrowing/widening bugs

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1994]
Neoverse-V2 was announced today: https://www.anandtech.com/show/17575/arm-announces-neoverse-v2-and-e2-the-next-generation-of-arm-server-cpu-cores

As far as we can tell it looks like they reduced the SVE register size from 256-bit to 128-bit. This means our use of the vixl simulator is going to be used quite a bit longer than expected.

We should solve the issues in the simulator for the couple of failing tests so we don't trip over them in the future. At least until we have real SVE 256-bit hardware in CI.

**Comment by Sonicadvance1** [comment]
Putting this on LC since they will likely hit this issue before anyone else.

**Comment by lioncash** [comment]
Whoops! Meant to close this once https://github.com/FEX-Emu/FEX/pull/2087 was merged, since that fixes this issue.
