### ISSUE TITLE
Random  stuck  in termux

### ISSUE THREAD

**Issue by jinshulumengchuang** [FEX-Emu/FEX#2121]
Hi, i am running  fex2210  in termux. I use termux-chroot to solve system call problem in android. FEX 2210 runs fast and has great compatibility on my device ,but sometimes stucks here.Can anyone help me debug this problem?
Thanks

**Comment by Sonicadvance1** [comment]
What are you trying to run that gets stuck?
Without more information it is hard to help debug it.

**Comment by jinshulumengchuang** [comment]
> What are you trying to run that gets stuck? Without more information it is hard to help debug it.

**Comment by jinshulumengchuang** [comment]
> What are you trying to run that gets stuck? Without more information it is hard to help debug it.

The most frequently used program is wine. Stucks can happen when using integrated programs and other programs. wineboot stucks many times, winecfg about three times,7-zip stucks once when i trying to benchmark 
Also stuck once when I using apt.

**Comment by jinshulumengchuang** [comment]
> What are you trying to run that gets stuck? Without more information it is hard to help debug it.
Here is some  info about my device 
ANDROID 12
termux 0.118
FEX2210
wine-7.19
Dimensity 9000

**Comment by jinshulumengchuang** [comment]
to solve this problem, you should use FEX from ppa in a proot enviroment, and set Force32BitAllocator=1
