### ISSUE TITLE
Ubuntu 22.10 Support?

### ISSUE THREAD

**Issue by FerLuisxd** [FEX-Emu/FEX#2140]
The new ubuntu [version](https://releases.ubuntu.com/kinetic/) was recently release and would be awsome for this to be compatible with it

**Comment by Sonicadvance1** [comment]
We already have the PPA setup with Ubuntu Kinetic.
I added the Kinetic rootfs to our server today so the FEXRootFSFetcher can grab it.
Our automated install script has been updated to support Kinetic autosetup as well.
