### ISSUE TITLE
Build fails - CMake Error

### ISSUE THREAD

**Issue by CalcProgrammer1** [FEX-Emu/FEX#2220]
On Asahi Linux, I tried installing both from the AUR (fex-emu and fex-emu-git) as well as manually following the wiki directions.  In all cases, I get the following CMake error:

ModuleNotFoundError: No module named 'pkg_resources'
CMake Error at CMakeLists.txt:298 (strong): string sub-command STRIP requires two arguments.

**Comment by Sonicadvance1** [comment]
Looks like a python3 script fails to categorize your CPU for some reason.
Either python3 executable missing or something else.

Also FEX can't run on systems with 16K page sizes, so you're likely to hit problems unless you're running their 4K page size kernel.

**Comment by Sonicadvance1** [comment]
Found out where this is coming from. This is due to the `python-setuptools` package not being installed.
The AUR will be updated to include this package in the next release.
