### ISSUE TITLE
how to dump the generated arm64 aot file ?

### ISSUE THREAD

**Issue by baikaishiuc** [FEX-Emu/FEX#2289]
Hi

According the article [Reverse-engineering Rosetta 2 part1: Analyzing AOT files and the Rosetta 2 runtime](https://ffri.github.io/ProjectChampollion/part1/) , the M1 rosetta system will generate a arm64 aot file when run x64 file.

this is a simple x86_64 hello example in my m1 :
<img width="779" alt="image" src="https://user-images.githubusercontent.com/618485/209296032-08b6ab24-2893-47a9-8fcb-e9b600f2db2e.png">

this is the generated arm64 file:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/618485/209296135-f629da4e-932f-4c80-91aa-248c62468f80.png">

so, In FEX, Is it will generate some Intermediate format file , like IR-aot, arm64 aot file , to simpify debugging , analyzing,  optimizing ? how to enable or dump it ?

**Comment by Sonicadvance1** [comment]
Currently we don't have any offline tooling support for reading the various cache files that FEX produces.
This hasn't been a high priority for us since code caching isn't yet stable.

**Comment by baikaishiuc** [comment]
> Currently we don't have any offline tooling support for reading the various cache files that FEX produces. This hasn't been a high priority for us since code caching isn't yet stable.

OK. thank you. 

First question, what method now you use to debug generated cache file ? have a article introduce it ?

Second question,  I read the article https://wiki.fex-emu.com/index.php/Development:Debugging_Crash

the cache file it be mapped in the memory , so you can use gdb disassembly it, can you publish the segfault_test source code ?

**Comment by Sonicadvance1** [comment]
> First question, what method now you use to debug generated cache file ? have a article introduce it ?

Just raw gdb debugging for now.

> the cache file it be mapped in the memory , so you can use gdb disassembly it

Once the JIT loads it from cache, it is easy enough to use gdb to disassemble it. Just need to add some debug logs for where it ends up in memory.

> can you publish the segfault_test source code ?

Just a basic program that forces a fault on start so it is easy to test.
```cpp
int main(int argc, char **argv) {
  char *Text = argv[argc];
  Text[0] = 'c';
  return 0;
}
```

**Comment by baikaishiuc** [comment]
> > First question, what method now you use to debug generated cache file ? have a article introduce it ?
> 
> Just raw gdb debugging for now.
> 
> > the cache file it be mapped in the memory , so you can use gdb disassembly it
> 
> Once the JIT loads it from cache, it is easy enough to use gdb to disassemble it. Just need to add some debug logs for where it ends up in memory.
> 
> > can you publish the segfault_test source code ?
> 
> Just a basic program that forces a fault on start so it is easy to test.
> 
> ```c++
> int main(int argc, char **argv) {
>   char *Text = argv[argc];
>   Text[0] = 'c';
>   return 0;
> }
> ```

ok, thank you, That is what I want.
