### ISSUE TITLE
need help automating FEXRootFSFetcher

### ISSUE THREAD

**Issue by cobalt2727** [FEX-Emu/FEX#2356]
I went back and tested my [automatic build script](https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/FEX.sh) for FEX to make sure it was still working and I've hit a roadblock - there doesn't seem to be any way to automate choosing a RootFS. Is there any way to have it always pull the latest/most recommended version without any input from the user?

![image](https://user-images.githubusercontent.com/60624944/215194515-b40dc25a-0bfd-40c9-9933-3fc7ad6b2534.png)
(it doesn't even display the options if this line is run from within the script itself.)

**Comment by Sonicadvance1** [comment]
Would likely need to use the `--distro-name` and `--distro-version`if auto detection doesn't have a corresponding rootfs available to download.

Could probably add a `--first` option to get the top selection in the list, which I have been ordering to be the "newest" version of Ubuntu.
Not sure how that will work if we add Arch or something to the list.

**Comment by cobalt2727** [comment]
looks like I can hack my way around this with `yes 1 | FEXRootFSFetcher -y`


...so maybe just put this hypothetical Arch rootfs at the bottom of the list or something? 😆

![image](https://user-images.githubusercontent.com/60624944/215248334-14c01497-5b89-4e48-b364-fdae31a6c26e.png)

**Comment by Sonicadvance1** [comment]
Well, assuming we filter based on only `--distro-name` then a `--first` option would still make sense, since I plan on keeping Ubuntu sorted from latest version to oldest.

**Comment by cobalt2727** [comment]
Makes sense. Could you modify the failed unsquashfs prompt to follow the `-y` parameter and just automatically advance with using it as-is? I did notice I had to manually do that despite adding the parameter...
