### ISSUE TITLE
FEX fails to build on Alpine Linux (musl)

### ISSUE THREAD

**Issue by Newbytee** [FEX-Emu/FEX#2357]
:wave: Hi!

On Alpine Linux, trying to build FEX results in the compilation halting with the following error:
```
/home/user/FEX/Source/Tools/FEXServer/ProcessPipe.cpp:477:60: error: use of undeclared identifier 'POLLREMOVE'
                  .events = POLLIN | POLLPRI | POLLRDHUP | POLLREMOVE,
                                                           ^
```
`POLLREMOVE` seems to come from the header `poll.h`, which I assume resolves to `/usr/include/poll.h`. `/usr/include/poll.h`, in turn, includes `<bits/poll.h>`. On Fedora with glibc, this file defines `POLLREMOVE`, but on Alpine Linux with musl it seems like this file is empty (like, completely empty) and as such `POLLREMOVE` ends up undefined.

In the FEX 2203 changelog you mentioned musl compilation being fixed (https://fex-emu.com/FEX-2203/). How was this tested? Am I missing something?

**Comment by Sonicadvance1** [comment]
Sorry, we don't test running on musl daily or even in our CI. So it looks like compiling on a musl host has broken since that time.

**Comment by Newbytee** [comment]
Do you know what kind of system was used to test musl suport?

**Comment by Sonicadvance1** [comment]
It was likely a chroot.

**Comment by Newbytee** [comment]
Yeah, but what distribution?

**Comment by Sonicadvance1** [comment]
I don't recall, it was nearly a year ago when I did it.

**Comment by neobrain** [comment]
#2370 removed the use of POLLREMOVE and #2380 fixed other build problems on Alpine, so I'm assuming it's working now. If you know any other issues, feel free to create a new report about them.
