### ISSUE TITLE
use fex-emu in android studio

### ISSUE THREAD

**Issue by saman-aliveisi** [FEX-Emu/FEX#2397]
hi all
I wanted to add fex-emu in android studio and create a new application (.apk)
But I don't know how to use it in Android Studio
If you have any examples or tips, please let me know

**Comment by Hacker1245** [comment]
you do know this is a linux program right?

**Comment by saman-aliveisi** [comment]
Yes, 
I mean is to run fex-emu under Termux with proot (without porting for android) that can be run on Android device (apk file).

**Comment by neobrain** [comment]
Android is not a supported platform.
