### ISSUE TITLE
use binfmt.d rather than binfmts for better compatibility

### ISSUE THREAD

**Issue by rhjdvsgsgks** [FEX-Emu/FEX#2417]
binfmts is only available on debian based distro. which isn't friendly to other distro. i prefer switch to [binfmt.d](https://www.freedesktop.org/software/systemd/man/binfmt.d.html) (which is a part of systemd, available on most of distro) and keep binfmts for debian only

**Comment by Sonicadvance1** [comment]
I would be fine with supporting more ways to install a binfmt handler. We already support two different ways. Which Distros use this way though?
I would like to know so we can test it when implementing support.

**Comment by neobrain** [comment]
Closing since there hasn't been any activity. We can reopen this one if you want to elaborate on your use case though.

**Comment by teohhanhui** [comment]
Fedora uses `/usr/lib/binfmt.d`, and the conflicting files would be:

```
/usr/lib/binfmt.d/box64.conf
/usr/lib/binfmt.d/box86.conf
/usr/lib/binfmt.d/qemu-i386-static.conf
/usr/lib/binfmt.d/qemu-x86_64-static.conf
```

**Comment by alyssarosenzweig** [comment]
Reopening, this is a blocker for Fedora packaging.
