### ISSUE TITLE
ninja clean fails with `Cleaning... ninja: error: remove(unittests/ASM): Directory not empty`

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#243]

**Comment by Kamaropoulos** [comment]
There is an issue (#1690) and PR (#1334) about this on the [ninja](https://github.com/ninja-build/ninja/) repo but it was never merged.

(Didn't link because the reference would appear on the original repo)

**Comment by Sonicadvance1** [comment]
Looks like this is impossible to fix until cmake fixes something on their end.
We are tracking all generated files on our end and even the `ADDITIONAL_CLEAN_FILES` target attribute doesn't let us take care of CMake's residual files it leaves behind.
```ryanh@Ryan-TR2:/mnt/Work/Work/work/FEXNew/Build$ tree unittests/ASM/
unittests/ASM/
├── CMakeFiles
├── cmake_install.cmake
└── CTestTestfile.cmake```
Workaround for now is to blow away the unittests folder if you want a full clean I believe.

**Comment by Sonicadvance1** [comment]
This has been fixed for a while now. Not sure when it was fixed.
