### ISSUE TITLE
Archlinux ARM stuck on FEXBash under android chroot

### ISSUE THREAD

**Issue by mio-19** [FEX-Emu/FEX#2441]
![Screenshot_2023-02-26-09-22-49-953_com termux-edit](https://user-images.githubusercontent.com/57285379/221387211-2f7bb993-ed76-410d-8e58-1016031e7c81.jpg)
![Screenshot_2023-02-26-09-23-28-739_com termux-edit](https://user-images.githubusercontent.com/57285379/221387237-fc2bba14-eaa5-4e97-a058-523fb578d70f.jpg)

**Comment by neobrain** [comment]
Not sure what problem exactly you're describing, but Android is not a supported platform.
