### ISSUE TITLE
Crash Bandicoot 4 uses `PCMPESTRI` unconditionally.

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2573]
First game I have found that uses it even when SSE4.2 CPUID bit isn't exposed.
Steam page: https://store.steampowered.com/app/1378990/Crash_Bandicoot_4_Its_About_Time/

Likely want to implement this initially as a C fallback, but there should be some investigation in to optimizing it to SVE MATCH plus predicate twiddling since even with SVE-128bit it might be more optimal.

**Comment by lioncash** [comment]
PCMPESTRI and VPCMPESTRI support was added in #2632
