### ISSUE TITLE
FEXBash or FEXInterpreter not working

### ISSUE THREAD

**Issue by FussyCone** [FEX-Emu/FEX#2642]
When i try to run FEXBash or FEXInterpreter after installing FEX-Emu on Termux It gives me Segmentation fault error.
What can it be this error?
 

-I have Installed ubuntu with the comand

proot-distro install ubuntu

   

-Ubuntu login

proot-distro login --user root ubuntu --shared-tmp

-And installed FEX-Emu

sudo apt update

sudo apt install software-properties-common

curl --silent https://raw.githubusercontent.com/FEX-Emu/FEX/main/Scripts/InstallFEX.py --output /tmp/InstallFEX.py && python3 /tmp/InstallFEX.py && rm /tmp/InstallFEX.py

![Screenshot_20230424-005826](https://user-images.githubusercontent.com/42359324/233898378-6d4bb75f-aaf6-45d3-8d4e-53b9cf1d98a4.png)

**Comment by neeeerrd** [comment]
I have the same issue.

**Comment by neobrain** [comment]
We're happy to integrate technical fixes for Termux, but it's not a platform we actively support.
