### ISSUE TITLE
Does this emulator run the Rust Game Dedicated server?

### ISSUE THREAD

**Issue by shadowremove** [FEX-Emu/FEX#2675]
Does this emulator run the Rust Dedicated Game server? 
Rust is a multiplayer survival video game

**Comment by nadirali01** [comment]
if i install Fex Emu in my ARM64 Server then rust server work? anyone try it ?

**Comment by daeeros** [comment]
++ same question

**Comment by neobrain** [comment]
If you find any issues with FEX on this specific use case, feel free to let us know. This isn't a place to request testing or support, though.
