### ISSUE TITLE
How to install on Termux Proot?

### ISSUE THREAD

**Issue by nerdydumbykier** [FEX-Emu/FEX#2682]
Hi, I was wondering how do I get FEX installed on Termux Proot. I can use box86 but I wanted to try FEX out.

Thanks..

**Comment by seisdr** [comment]
For Ubuntu 20->22.04 you can run 
`curl --silent https://raw.githubusercontent.com/FEX-Emu/FEX/main/Scripts/InstallFEX.py --output /tmp/InstallFEX.py && python3 /tmp/InstallFEX.py && rm /tmp/InstallFEX.py`
To install it, however Android is not a supported platform

**Comment by neobrain** [comment]
As noted, you're on your own when it comes to running FEX on Android.
