### ISSUE TITLE
Illegal instruction when run Unixbench binary

### ISSUE THREAD

**Issue by ChanthMiao** [FEX-Emu/FEX#2695]
**What Program**
UnixBench: <https://github.com/kdlucas/byte-unixbench.git>.

Precompiled binary tarball from [here](https://mega.nz/file/2Ap2yLpa#fhrsi1Weh8jRPx54ccCktZptN-TuQgGaZDxaNACoA_o)

**Describe the bug**

I try to run unixbench with FEX-2305 in a kunpeng920(ARMv8.2), but failed with Illegal instruction.
It seems that when run FEX with  a host that `SupportsAVX = false` cause this. There may be something wrong with current OpcodeDispatcher.

**To Reproduce**
1. Compile UnixBench in x86 machine, or just download the [precompiled tarball](https://mega.nz/file/2Ap2yLpa#fhrsi1Weh8jRPx54ccCktZptN-TuQgGaZDxaNACoA_o).
2. Set `"EnableAVX": "0"` in Config.json
3. Run `/build/Bin/FEXLoader -- /path/to/byte-unixbench/UnixBench/pgms/dhry2`

**Expected behavior**
print help info normally.
```txt
Usage: ../x86/byte-unixbench/UnixBench/pgms/dhry2 duration
```

**Screenshots and Video**
```txt
[ERROR] Invalid or Unknown instruction: VMOVDQA 0x0
[ERROR] Invalid or Unknown instruction: VMOVUPS 0x0
[ERROR] Invalid or Unknown instruction: VMOVAPS 0x0
Illegal instruction
```

**System information:**
 - OS: Debian bullseye container
 - CPU/SoC: [kunpeng920](https://www.hisilicon.com/en/products/Kunpeng/Huawei-Kunpeng/Huawei-Kunpeng-920)
 - RootFS used: Self Created Debian bullseye  Rootfs
 - FEX version: (FEXGetConfig --version) [FEX-2305]
 - Thunks Enabled: [No]

**Additional context**
 - Is this an x86 or x86-64 program: [x86-64]
 - Does this reproduce on x86-64 host with FEX: [Untested]
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: [Untested and Unrelated]

**Comment by Sonicadvance1** [comment]
Looks like this program is using AVX, which your CPU can't support emulation of.
Either the program needs to be recompiled without AVX usage, or if it unconditionally uses it then there is nothing that can be done.

**Comment by ChanthMiao** [comment]
Can FEX convert one AVX instruction into several non-avx instruction to make it work well.

**Comment by Sonicadvance1** [comment]
No it can not. We have elected to not emulate 256-bit vector instructions using 128-bit operations. If the hardware doesn't support comparable features then qemu might as well as be used instead.

**Comment by ChanthMiao** [comment]
So, it is not a bug, but a designed behavior?

**Comment by Sonicadvance1** [comment]
Correct

**Comment by ChanthMiao** [comment]
Ok, just close this issues.
