### ISSUE TITLE
wine taskmgr crashing

### ISSUE THREAD

**Issue by mio-19** [FEX-Emu/FEX#2697]
```
FEXBash
FEXBash-user@penguin:~> wine taskmgr
0050:err:ole:start_rpcss Failed to start RpcSs service
wine: Unhandled page fault on read access to 00000068 at address 007C5B09 (thread 0024), starting debugger...
Can't attach process 0020: error 5
Segmentation fault (core dumped)
```

fex-emu 2305-1 on archlinux arm

rootfs: ubuntu 22.04

**Comment by Sonicadvance1** [comment]
Works here with wine 7.0 provided in the Ubuntu image, and FEX-2306 plus some commits.
Not sure why it doesn't work for you with this little information.
![Screenshot 2023-06-28 10-01-26](https://github.com/FEX-Emu/FEX/assets/1018829/d6a9082f-bce0-4bee-99e0-f3aad654793d)
