### ISSUE TITLE
[Game]: Garrys Mod Dedicated Server > Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by daeeros** [FEX-Emu/FEX#2727]
**What Game**
The game name.
A link to the storefront where to get the game. GOG, Steam, Itch.io, etc
Garrys Mod Dedicated Server
**Describe the bug**
I installing server from linuxgsm like here: https://linuxgsm.com/servers/gmodserver/
But i getting errora after running, and not like this game, 1 day ago i try to setup rust server, and i get the same error(

```
FEXBash-gmodserver@minecraft:~> ./gmodserver install
fetching GitHub core_trap.sh...OK
fetching GitHub _default.cfg...OK
copying _default.cfg...OK
fetching GitHub check_ip.sh...OK
fetching GitHub info_game.sh...OK
fetching GitHub common.cfg...OK
fetching GitHub secrets-common.cfg...OK
fetching GitHub gmodserver.cfg...OK
fetching GitHub secrets-gmodserver.cfg...OK
fetching GitHub linuxgsm.sh...OK
fetching GitHub core_getopt.sh...OK
fetching GitHub command_install.sh...OK
fetching GitHub check.sh...OK
fetching GitHub check_version.sh...OK
fetching GitHub check_tmuxception.sh...OK
fetching GitHub check_permissions.sh...OK
fetching GitHub check_glibc.sh...OK
fetching GitHub info_distro.sh...OK
fetching GitHub check_system_requirements.sh...OK
Segmentation fault (core dumped)
```

**To Reproduce**
Run this commands:

```
FEXBash
wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver
./gmodserver install
```

**Expected behavior**
And after i getting error: Segmentation fault (core dumped)

**System information:**
(This is free oracle vds) (Ampere)

 OS: Ubuntu 20.04 focal
Kernel: aarch64 Linux 5.15.0-1037-oracle
Shell: bash 5.0.17
Disk: 12G / 206G (6%)
CPU: 3.0 GHz Ampere® Altra™ (4x)
RAM: 23988MiB

 - OS: [eg: Ubuntu 21.10]
 - CPU/SoC: [eg: Snapdragon 888, Intel Core i8-12900k]
 - Video driver version: [eg: OpenGL ES 3.2 Mesa 22.0.0-devel (git-9ff086052a)]
 - RootFS used: Installed from FEXBash
 - FEX version: FEX-2301
 - Thunks Enabled: [Yes/No]: 

**Additional context**
 - Is this an x86 or x86-64 game: [x86/x86-64/Both]
 - Does this reproduce on x86-64 host with FEX: [Yes/No/Untested]
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: [Yes/No/Untested]
 - Is this a Vulkan game: [Yes/No/Unknown]
   - If Yes, What is your Vulkan driver:

**Comment by Sonicadvance1** [comment]
If this is using FEX installed through our PPA (Which seems to be the case from the FEX-2301 version) then there was a fairly nasty bug that was fixed this month that will end up being in the 2307 version when it releases.

Additional problems come up though.
1. Ubuntu 20.04 Focal is no longer getting FEX updates due to old compiler. So you need to update your Distro.
2. linuxgsm checks for installed dependencies and can't get all the way through its installation. So manual installation will be required regardless.

Manual installation of gmod should work fine from last I checked with the newer version of FEX. This is harder though.

**Comment by daeeros** [comment]
> If this is using FEX installed through our PPA (Which seems to be the case from the FEX-2301 version) then there was a fairly nasty bug that was fixed this month that will end up being in the 2307 version when it releases.
> 
> Additional problems come up though.
> 
> 1. Ubuntu 20.04 Focal is no longer getting FEX updates due to old compiler. So you need to update your Distro.
> 2. linuxgsm checks for installed dependencies and can't get all the way through its installation. So manual installation will be required regardless.
> 
> Manual installation of gmod should work fine from last I checked with the newer version of FEX. This is harder though.

When i try to manualy, when server is strting, i getting err about rootfs, but is installed and used, did you now what this error?

```
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
Invalid or Unsupported elf file.
This is likely due to a misconfigured x86-64 RootFS
Current RootFS path set to ''
RootFS path doesn't exist. This is required on AArch64 hosts
Use FEXRootFSFetcher to download a RootFS
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Thu Jun 29 08:36:50 UTC 2023: Server restart in 10 seconds
^CThu Jun 29 08:36:51 UTC 2023: Server Quit

FEXBash-ubuntu@france:~/Steam/gmod> FEXRootFSFetcher
RootFS is already in use. Do you want to check the download list?
Response {y,yes,1} or {n,no,0}
```

**Comment by daeeros** [comment]
> Sounds like you're running a stale FEXServer that didn't pick up the new rootfs configuration. Stopping all FEX instances and restarting the FEXServer should pick up the new version. `FEXServer -k` will force kill the old FEXServer.
> 
> Either that or the these messages are from different user accounts on Linux, and since the rootfs config is per-user it isn't setup on the other user.

Thank you :3 have a nice day

**Comment by Sonicadvance1** [comment]
Was resolved.
