### ISSUE TITLE
Library support for C++

### ISSUE THREAD

**Issue by IHaveAPear** [FEX-Emu/FEX#2736]
Hi,
I notice that there are only C libraries in FEX Thunklib. I wonder that if FEX is able to support C++ libraries, and whether there are difficulties in supporting C++ libraries. I would be grateful for your reply.

**Comment by Sonicadvance1** [comment]
FEX doesn't currently support a generic solution for thunking C++ libraries. It requires handling things like C++ class vtable pointers which is difficult.
Most libraries that would be interesting for thunking aren't C++ though which is good since the ABI isn't stable there.

**Comment by neobrain** [comment]
Looks like there's nothing to do here. Feel free to join us on Discord or IRC for general discussions.
