### ISSUE TITLE
not finding execution instructions to be very clear

### ISSUE THREAD

**Issue by develperbayman** [FEX-Emu/FEX#2744]
i installed fex installed and extracted the rootfs commands not working im on ubuntu on orange pi 5 is there a gui frontend the wiki just seems to cover setup it gave instructions at the end of the install but then i had a hard drive mounting issue so i had to switch my focus now im lost

**Comment by neobrain** [comment]
If you have specific suggestions on improving the documentation, please let us know. While there's always room for improvement, this specific report is a bit difficult to action on.
