### ISSUE TITLE
java crashing on shutdown on arm64

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2752]
Doesn't seem to happen on an x86 host for some reason, but on AArch64 it seems to be the case that it will close on shutdown.

Causes [Project Zomboid](https://store.steampowered.com/app/108600/Project_Zomboid/) to fail early and seemingly a simple enough test of just running `jre64/bin/java -version` is enough to see it.

**Comment by turbocool3r** [comment]
I've faced the same issue when trying to run the ip-generate tool from Quartus Prime which calls into java internally. Just executing the bundled java with the `-version` flag reproduces this as well. I was running this in an Ubuntu 22.04.1 virtual machine with the Linux 6.2.0-32-generic kernel. The Quartus version is 22.1.

The crash looks as follows if that helps:
```
Segmentation fault (core dumped)

Program received signal SIG63, Real-time event 63.
0x0000fffff7be734c in ?? () 
(gdb) bt
#0  0x0000fffff7be734c in ?? ()
#1  0x3e899cd7289845bc in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by turbocool3r** [comment]
Thanks!
