### ISSUE TITLE
Missing GPR aliases in ARMEmitter

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2836]
- [x] tst
- [x] bfc
- [x] bfxil
- [x] cinc
- [x] cinv
- [x] csetm
- [x] stadd{a,al,l,}{b,h,} -mishmash of these
- [x] strclr{a,al,l}{b,h,} -mishmash of these
- [x] streor{a,al,l}{b,h,} -mishmash of these
- [x] strset{a,al,l}{b,h,} -mishmash of these
- [x] stsmax{a,al,l}{b,h,}
- [x] stsmin{a,al,l}{b,h,}
- [x] stumax{a,al,l}{b,h,}
- [x] stumin{a,al,l}{b,h,}
- [x] ngc
- [x] ngcs
- [x] sbfiz
- [x] ubfiz

Seems to be all of the missing GPR aliases from a quick scan of the ARM ARM.

**Comment by lioncash** [comment]
Closing, since this is now completed
