### ISSUE TITLE
List of games that need RDTSC scaling

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2906]
It has been reported that some games will use RDTSC, making the assumption that it ticks at the rate of the nominal CPU frequency. Ideally the games would measure the RDTSC tick rate or on modern Intel platforms read the CPUID status bits for this.

We can potentially scale the RDTSC to a ratio of the "nominal" cpu frequency. Once ARMv8.6/9.1 chips come with a 1Ghz frequency, we can easily do a 1.5x/2x/3x scale rather than the MASSIVE scale required for today's chips of 19.2Mhz.

We need to keep a list of games that need this workaround since I have noticed a few that it seems to have issues.

**Seemingly confirmed games**
- Horizon Zero Dawn

**Potential games with this issue**
- Warhammer 40k: Gladius - Relics of war (Or maybe one of the other Warhammer games?)

**Comment by Sonicadvance1** [comment]
All Unreal Engine 5 games will likely need rdtsc scaling for systems that have a cycle counter slower than 1Ghz.

**Comment by alyssarosenzweig** [comment]
#3430 merged, so closing I think
