### ISSUE TITLE
SPDX in FEX's sources

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3086]
FEX needs to slap SPDX in to all of its sources to make mixed license files less of an issue.

This should just be putting `// SPDX-License-Identifier: MIT` on the first line of every FEX file.
Probably want to make sure it doesn't conflict with with the `Scripts/doc_outline_generator.py` thing that is run every release.

Let's start a discussion about doing this to see if anyone has any comments about this.
- Should it just be `// SPDX-License-Identifier: MIT`  ?
- Any concerns?

I personally have never used SPDX so I don't know if there are any particular problems that could crop up.

**Comment by bylaws** [comment]
`// SPDX-License-Identifier: MIT` should be fine, some other projects choose to include something like `// SPDX-FileCopyrightText: Copyright (year) (name)` as well but I'm unsure whether that's necessary

**Comment by lioncash** [comment]
I think just the license identifier would be appropriate since most (all?) of our source files don't have any established year info that needs to be preserved

**Comment by neobrain** [comment]
Adding SPDX is appreciated, no particular opinions on it other than that :)

Unless there's technical reasons to pick something else, `// SPDX-License-Identifier: MIT` sounds good to me.
