### ISSUE TITLE
InstCountCI: Support multiple instruction tests

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3146]
Right now we can't test simple things like cost-prop optimizations. We don't really want huge tests in this CI but smaller things make sense.
eg:
```asm
mov rax, 0
mov rcx, 0
cpuid
```
This would hit a more optimal case but our CI can't show it yet.

This will require implementing some way to dynamically choose block size to compile  and just a list in the json. Likely changing the instruction name in to just a tag.

**Comment by alyssarosenzweig** [comment]
FWIW I would love to get hot blocks from real games (#2688 #2563 etc) in instcountci if that's feasible
