### ISSUE TITLE
BOINC: Couldn't connect to FEXServer socket

### ISSUE THREAD

**Issue by henfredemars** [FEX-Emu/FEX#3197]
**What Game**
This is not a game, but rather I'm evaluating the suitability of FEX to run scientific computing applications. These are CPU bound and do not have graphics. QEMU-user works, but FEX might offer better performance. 

This software might not be relevant to your project goals. In that case, I would appreciate any recommendations of debugging the issue. 

A link to the storefront where to get the game. GOG, Steam, Itch.io, etc

Boinc client (host native): https://boinc.berkeley.edu/download.php
Application (x86_64, downloaded by the client at runtime, no direct download): https://milkyway.cs.rpi.edu/milkyway/apps.php

**Describe the bug**
Running MilkyWay directly from the CLI works great via the binfmt_misc mechanism. 
However, I get this error when BOINC tries to launch the application binary using the same arguments:

`[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket 111 Connection refused
[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket 111 Connection refused
[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket 111 Connection refused
[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket 111 Connection refused
[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket 111 Connection refused
[ERROR] Couldn't connect to FEXServer socket 114.FEXServer.Socket after launching the process
[ERROR] FEXServerClient: Failure to setup client`

Boinc runs as user `boinc` rather than my user. I'm not sure if this can explain the error. 

**To Reproduce**
1. Install BOINC.
2. Modify `/etc/boinc/cc_config.xml` to define <alt_platform> to force download of x86_64 executables. 
3. Register for MilkyWay and wait for client to download the app.
4. Observe in /var/lib/boinc/projects/milkway/<binary name> that binary appears to initialize correctly when run directly.
5. Observe BOINC reports task failure. Log messages are unfortunately submitted to MilkyWay servers and can be pulled from there in the task listing for the registered machine. 

I need to explore a more precise and self-contained procedure, but I'm more hoping for general ideas rather than for someone to invest their valuable time trying to reproduce a non-game error. 

**Expected behavior**
It shouldn't fail when boinc runs the binary given that it works when run by a normal user. 

**System information:**
 - OS: Ubuntu 22 LTS
 - CPU/SoC: Raspberry Pi 4
 - Video driver version: N/A
 - RootFS used: Default
 - FEX version: FEX-2310. I can obtain a more accurate value at a later time upon request. 
 - Thunks Enabled: Default, not sure. 

**Additional context**
 - Is this an x86 or x86-64 game: x86-64
 - Does this reproduce on x86-64 host with FEX: Untested
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: Untested
 - Is this a Vulkan game: No

Thank you for your time.

**Comment by CallumDev** [comment]
You need to run FEXRootFSFetcher as the boinc user, as the rootfs is only present on your local user

**Comment by henfredemars** [comment]
You are awesome! Thank you. I did not know it was user specific.
