### ISSUE TITLE
'ubuntu 20.04' is not a supported distro

### ISSUE THREAD

**Issue by aletzi1** [FEX-Emu/FEX#3359]
Trying to run installer script:

ubuntu@testsite~$ curl --silent https://raw.githubusercontent.com/FEX-Emu/FEX/main/Scripts/InstallFEX.py --output /tmp/InstallFEX.py && python3 /tmp/InstallFEX.py && rm /tmp/InstallFEX.py
'ubuntu 20.04' is not a supported distro

Any workaround ?

**Comment by Sonicadvance1** [comment]
Upgrading to a version of Ubuntu that is newer than 20.04 is the workaround.
