### ISSUE TITLE
steamcmd: When I tried to run "steamcmd", I received an error "./teamcmd. sh: line 38: 8511 Illegal instruction $DEBUGGER" $STEAMEXE "" $@ "

### ISSUE THREAD

**Issue by alatter** [FEX-Emu/FEX#3418]
**What Game**
steamcmd

When I tried to run "steamcmd", I received an error "./teamcmd. sh: line 38: 8511 Illegal instruction $DEBUGGER" $STEAMEXE "" $@ "

**To Reproduce**
I downloaded and successfully installed "fex emu armv8.4" from the PPA repository and followed the prompts to install rootfs. However, I encountered an error when attempting to run "steamcmd" in this environment

**Expected behavior**
I hope to find a solution to this problem, or to create my own rootfs package to solve this problem
**Screenshots and Video**
![image](https://github.com/FEX-Emu/FEX/assets/106290652/d54db152-6c2d-4d7d-b0d1-d4bc25b2f1ba)

**System information:**
 - OS: [eg: Ubuntu 23.10]
 - CPU/SoC: Snapdragon 855
 - RootFS used: [eg: Ubuntu 22.10 Official Rootfs]
 - FEX version: (FEXGetConfig --version) [FEX-2312.1]

**Additional context**

I am happy to add any details that I have missed

**Comment by Sonicadvance1** [comment]
This sounds like you might have installed the wrong FEX package. Your Snapdragon 855 device is only ARMv8.2 and not ARMv8.4, so it is likely hitting an instruction that doesn't exist on your CPU. I would recommend uninstalling the v8.4 package and installing the v8.2 one.

**Comment by alatter** [comment]
Sorry, I made a mistake. I'll try it out

**Comment by Sonicadvance1** [comment]
That is intentional. All the dependencies are already installed, Steam's startup script just complains for various reasons.
Setting a couple of environment variables before executing the script can help.
```
export STEAMOS=1
export STEAM_RUNTIME=1
```

**Comment by Sonicadvance1** [comment]
```bash
$ FEXBash
FEXBash-ryanh@buildbot-orin-2:~/Steam> ./steamcmd.sh
Redirecting stderr to '/home/ryanh/.local/share/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (4,350 of 59,782 KB)...
[  7%] Downloading update (9,210 of 59,782 KB)...
[ 15%] Downloading update (13,629 of 59,782 KB)...
[ 22%] Downloading update (17,657 of 59,782 KB)...
[ 29%] Downloading update (21,301 of 59,782 KB)...
[ 35%] Downloading update (24,987 of 59,782 KB)...
[ 41%] Downloading update (28,668 of 59,782 KB)...
[ 47%] Downloading update (32,466 of 59,782 KB)...
[ 54%] Downloading update (36,369 of 59,782 KB)...
[ 60%] Downloading update (42,975 of 59,782 KB)...
[ 71%] Downloading update (44,647 of 59,782 KB)...
[ 74%] Downloading update (46,560 of 59,782 KB)...
[ 77%] Downloading update (48,206 of 59,782 KB)...
[ 80%] Downloading update (49,828 of 59,782 KB)...
[ 83%] Downloading update (50,355 of 59,782 KB)...
[ 84%] Downloading update (52,152 of 59,782 KB)...
[ 87%] Downloading update (53,930 of 59,782 KB)...
[ 90%] Downloading update (56,110 of 59,782 KB)...
[ 93%] Downloading update (57,987 of 59,782 KB)...
[ 96%] Downloading update (59,782 of 59,782 KB)...
[100%] Downloading update (59,782 of 59,782 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
tid(37093) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/ryanh/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/ryanh/.local/share/Steam/logs'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(37105) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/ryanh/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/ryanh/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Steam>
```

Interesting, I don't get that problem here.

**Comment by alatter** [comment]
Can FEXRootFSFetcher only run as root user? How to enter FEXBash as an ordinary user?
![image](https://github.com/FEX-Emu/FEX/assets/106290652/764107f9-89a1-430a-a39c-deab669758a4)

**Comment by Sonicadvance1** [comment]
FEXRootFSFetcher can run as any user. It will just download the image in to the user's $HOME folder.
If it is failing to download the rootfs list from the server for a user then there is either an issue executing curl, or some firewall getting in the way of accessing https://rootfs.fex-emu.gg/RootFS_links.json

**Comment by alatter** [comment]
When I tried to download the relevant library for "steamcmd", I encountered the following error: progress stuck at 0% while "steamcmd" was verifying files
FEXBash-steam@localhost:~/steam> ./steamcmd.sh +login anonymous +app_update 1007 +quit
tid(23636) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x1) running, progress: 0.00 (0 / 0)
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (1866) : Thread synchronization object is unuseable
src/tier0/threadtools.cpp (1866) : Thread synchronization object is unuseable
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)
 Update state (0x81) verifying update, progress: 0.00 (0 / 73781292)

**Comment by Sonicadvance1** [comment]
Interesting, I also can't reproduce that here.
```bash
FEXBash-ryanh@buildbot-orin-2:~/Steam> ./steamcmd.sh +login anonymous +app_update 1007 +quit
tid(113153) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/ryanh/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/ryanh/.local/share/Steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 85.79 (63295532 / 73781292)
Success! App '1007' fully installed.
```

**Comment by alatter** [comment]
I found that even if I skip Steam's verification, it can still be used. Thank you for your help
