### ISSUE TITLE
Tekken 8 slow blocks

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3428]
The top 11 blocks of code consume 52.27% of the CPU time
![Image_2024-02-18_00-33-48](https://github.com/FEX-Emu/FEX/assets/1018829/058d3e1d-5bdf-4218-8536-f3fd34eb10c5)

Adding these hot blocks to instcountci will be good to do.

**Comment by Sonicadvance1** [comment]
All 11 blocks are the same RIP: 0x142b15562
![Image_2024-02-18_09-15-20](https://github.com/FEX-Emu/FEX/assets/1018829/19ace1fa-abd5-460d-8e8e-0b59e01c128d)
It's a timing based spin-loop!

**Comment by Sonicadvance1** [comment]
The emitted assembly.
```asm
   0x00007fff90e428a4:  udf     #84
   0x00007fff90e428a8:  adr     x0, 0x7fff90e428a4
   0x00007fff90e428ac:  str     x0, [x28, #184]
=> 0x00007fff90e428b0:  yield
   0x00007fff90e428b4:  mrs     x20, cntvct_el0
   0x00007fff90e428b8:  mov     w4, w20
   0x00007fff90e428bc:  lsr     x6, x20, #32
   0x00007fff90e428c0:  lsl     x6, x6, #32
   0x00007fff90e428c4:  orr     x4, x4, x6
   0x00007fff90e428c8:  sub     x4, x4, x16
   0x00007fff90e428cc:  sub     x26, x4, x29
   0x00007fff90e428d0:  eor     x27, x4, x29
   0x00007fff90e428d4:  cmp     x4, x29
   0x00007fff90e428d8:  cfinv
   0x00007fff90e428dc:  b.cs    0x7fff90e428b0  // b.hs, b.nlast
   0x00007fff90e428e0:  b       0x7fff90e4291c
   0x00007fff90e428e4:  blr     x0
   0x00007fff90e428e8:  .inst   0xf7efc148 ; undefined
   0x00007fff90e428ec:  udf     #32767
   0x00007fff90e428f0:  .inst   0x42b15575 ; undefined
   0x00007fff90e428f4:  udf     #1
   0x00007fff90e428f8:  udf     #116
   0x00007fff90e428fc:  udf     #0
   0x00007fff90e42900:  .inst   0x42b15562 ; undefined
   0x00007fff90e42904:  udf     #1
   0x00007fff90e42908:  udf     #0
   0x00007fff90e4290c:  udf     #32
   0x00007fff90e42910:  udf     #0
   0x00007fff90e42914:  udf     #0
```

**Comment by Sonicadvance1** [comment]
On my threadripper system r15 has a value of 1597 which at a 2.7Ghz cycle counter equals about 591 nanoseconds which is significantly lower

**Comment by Sonicadvance1** [comment]
`7.92%  [JIT] tid 22907             [.] 0x0000000142b15564`
Hottest block on my threadripper. Which of course is only showing total process time since the code isn't duplicated per thread.
Could be that the game is just burning more time because the longer wait period, or is stalled out waiting for other work. Hard to tell.

**Comment by Sonicadvance1** [comment]
Also panic spills at RIPs 0x142d25290 and 0x142d26470.
Likely some initializer/constructor from the repeating patterns. Could be because it is materializing a bunch of constants.

**Comment by Sonicadvance1** [comment]
The difference in cycles is spurious. Worker threads get set a "random" prime number of cycles to wait from a table of eight.

Table on Nvidia Orin with 31.25Mhz cycle counter
```
719 - 23008 ns
991 - 31712 ns
1237 - 39584 ns
1597 - 51104 ns
953 - 30496 ns
587 - 18784 ns
1439 - 46048 ns
```

Table on TR with 2.7Ghz cycle counter
```
719 - 266 ns
991 - 367 ns
1237 - 458 ns
1597 - 591 ns
953 - 352 ns
587 - 217 ns
1439 - 532 ns
```
So it was coincidental that the thread I was looking at on ARM had a larger number of cycles. This effectively means that the worker threads have a fixed amount of time they will busy wait.
On systems with slower cycle-counters like most ARM devices, this just causes them to spin in the code for longer periods of time.

We can't work around this without rdtsc scaling, which will affect every Unreal Engine 5 game. ARMv8.6/v9.1 can't come soon enough. A 1Ghz cycle counter makes this significantly less of an issue.

**Comment by alyssarosenzweig** [comment]
I just merged the RDTSC scaling PR, so closing I think
