### ISSUE TITLE
Ensure thunk generator generates "gen" folder

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#357]
Currently the thunk generator fails if the gen folder isn't generated
https://github.com/FEX-Emu/FEX/blob/master/ThunkLibs/GuestLibs/CMakeLists.txt#L13
https://github.com/FEX-Emu/FEX/blob/master/ThunkLibs/HostLibs/CMakeLists.txt#L6

Ensure this folder is created as part of the build script.

For an example for elsewhere creating the directory.
https://github.com/FEX-Emu/FEX/blob/955bdf296484827f6f8f67959dcbd51314eb8c37/unittests/ASM/CMakeLists.txt#L15

**Comment by skmp** [comment]
It is always generated w/ Ninja, but looks like MAKE doesn't handle it. Peculiar. I'll look into it

**Comment by Sonicadvance1** [comment]
Fixed by #525
