### ISSUE TITLE
Current X87 issues

### ISSUE THREAD

**Issue by pmatos** [FEX-Emu/FEX#3623]
This is just my list of the things I know are problematic but since they are fixed in my branch, I haven't patched upstream yet.

1. <del>Subtract and division has reverse operators incorrectly set: See https://github.com/FEX-Emu/FEX/pull/3547/commits/efa09a1f9b99f4323e7d280eb530bc1bac6fdcc5</del>
2. fst st(i) is not setting tag properly: See test https://github.com/FEX-Emu/FEX/blob/f15b7b0941d15655b3704122960e063490625259/unittests/ASM/X87/DD_D0_2.asm which fails with current upstream.
3. FXCH should set C1 to Zero: See https://github.com/FEX-Emu/FEX/pull/3547/commits/361fbcf93abdef1a40f1a6046acabec3f2b3775c
4. <del>There's some issue with top off by one in 64bits. D9_F7_F64.asm, RAX should end up with 0x4070000000000000 per my understanding. cc: @CallumDev </del>

**Comment by CallumDev** [comment]
It is likely the test may be faulty for 4. D9_F7_F64.asm does run and pass on the host runner, but I may have made a mistake in writing the test itself.

**Comment by pmatos** [comment]
> It is likely the test may be faulty for 4. D9_F7_F64.asm does run and pass on the host runner, but I may have made a mistake in writing the test itself.

I will spend some time looking into it.

**Comment by pmatos** [comment]
Point 2. addressed by #3714

**Comment by pmatos** [comment]
Point 3. addressed by #3715

**Comment by pmatos** [comment]
Point 1. was invalid. My mistake misunderstanding what the reverse template argument to fsub and fdiv means. fdiv + reverse != fdivr and fsub + reverse != fsubr. It just means that the argument during the fsub and fdiv computation need to be reversed and this happens due to how the arguments are loaded, and not because we are doing a fsubr or fdivr. I will make sure I add a comment to this effect in a future commit.

**Comment by pmatos** [comment]
> It is likely the test may be faulty for 4. D9_F7_F64.asm does run and pass on the host runner, but I may have made a mistake in writing the test itself.

This was my mistake looking into the example. Sorry for the noise. All good with X87F64 wrt this test at least. :)

Point 4. is invalid.

**Comment by pmatos** [comment]
I have addressed all points here. Closing.
