### ISSUE TITLE
Some posix tests are race happy

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#364]
Loads of tests do some sleeping or forking and sleeping.
Which this results is buggy racing.
We need special handling of these to stop them randomly breaking
Probably serializing the tests and maybe a small retry loop.

difftime-1-1 was one that I just saw as being a race.
Bunch of random signal tests are also race happy.

**Comment by Sonicadvance1** [comment]
4325 - conformance-interfaces-clock_nanosleep-10-1.test.int.posix (Failed)
	4339 - conformance-interfaces-clock_nanosleep-9-1.test.int.posix (Failed)
	4535 - conformance-interfaces-nanosleep-5-2.test.int.posix (Failed)
	4539 - conformance-interfaces-nanosleep-7-1.test.int.posix (Failed)
	4541 - conformance-interfaces-nanosleep-7-2.test.int.posix (Failed)

Also race happy

**Comment by phire** [comment]
Tests were using TGKILL and everything in the same group would get killed.
