### ISSUE TITLE
Fallout: New Vegas slow in-game due to x87 soft float

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3670]
Both its primary thread and another logic thread are maxing out two CPU cores due to x87 soft float.
This game requires softfloat because logic is otherwise broken with reduced precision mode.
- NPCs stop walking
- Character movement with keyboard does stutter stepping

```
Tested by walking outside of the starting house and staring directly at the floor.

// Primary Thread
// 27.2% - In X87 softfloat handlers

// Logic Thread? - Total 50.65%
// 7.58% - F80ADD
// 6.9% - softfloat_roundPackToExtF80
// 6.76% - F80SUB
// 5.60% - softfloat_subMagsExtF80
// 4.77% + 0.14% - F80CVT
// 4.62% + 0.18% - F80CVTTO
// 3.47% - softfloat_addMagsExtF80
// 3.33% - extF80_mul
// 2.77% - softfloat_roundPackToF32
// 2.06% - f32_to_extF80
// 1.65% - F80MUL
// 0.51% - F80CVTINT
// 0.31% - F80CMP
```

**Comment by pmatos** [comment]
Looks like another good benchmark for the work in #3547 . Thanks.

**Comment by Sonicadvance1** [comment]
Closing since recent vector instruction fixes actually fixed the broken game logic. Looks like it was some weird interaction between x87 and SSE/MMX. Also nothing really actionable other than tracking the knowledge that x87 is slow in this game.
