### ISSUE TITLE
Tohou: Luna Nights tile x87 precision issue

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3685]
For some reason when we run with x87 this game has tile rendering issues. When turning on x87 reduced precision the problem goes away.

This could be an issue with us not handling x87 precision modes correctly?

![Screenshot 2024-06-04 04-36-50](https://github.com/FEX-Emu/FEX/assets/1018829/abac1d79-4141-41a7-9473-d9f08f6dca19)

**Comment by pmatos** [comment]
Another for my list to check. cc #3547

**Comment by Sonicadvance1** [comment]
Retested because of recent vector instruction fixes. Behaviour is unchanged.

**Comment by pmatos** [comment]
I can still reproduce this. I will try to understand what's going on.

**Comment by Sonicadvance1** [comment]
Fixed by #4101 woo
