### ISSUE TITLE
Why is FEX not working for me?

### ISSUE THREAD

**Issue by robotman40** [FEX-Emu/FEX#3696]
I compiled FEX (from git) on my Raspberry Pi 4 and I am unable to launch Wine, Discord, Steam, etc. Are these programs known to be problematic with FEX or did I potentially do something wrong. If the latter, then I'll do whatever is needed to show my end.

**Comment by pmatos** [comment]
I would say that it is probably some issue on your end. If you share some details, maybe we can understand what's going on. Common issues is missing dependencies, missing rootfs, etc.

**Comment by neobrain** [comment]
There's no actionable information in this report. For support, please visit the FEX Discord.
