### ISSUE TITLE
Rootfs cannot be setted correctly

### ISSUE THREAD

**Issue by asahiqin** [FEX-Emu/FEX#3895]
In FEXConfig, the rootfs is Archlinux,but FEXBash is Ubuntu_22_04

**Comment by Sonicadvance1** [comment]
Make sure to restart all instances of FEX and FEXServer when the rootfs config has changed. It is "sticky" and will stay the old rootfs option until FEXServer is closed and restarted.

**Comment by asahiqin** [comment]
![Screenshot_2024-07-26-18-33-08-76_00df01c412509efb9bd6450c382822af.jpg](https://github.com/user-attachments/assets/73b5678f-0c78-4791-9a6e-9502b86c8fc6)

This is a screenshot,archlinux rootfs shouldn't have apt command,so I think it's also a ubuntu rootfs

**Comment by asahiqin** [comment]
> Make sure to restart all instances of FEX and FEXServer when the rootfs config has changed. It is "sticky" and will stay the old rootfs option until FEXServer is closed and restarted.

Thank you for help
