### ISSUE TITLE
src/tier0/threadtools.cpp (2036) : Assertion Failed: semaphore creation failed Invalid argument

### ISSUE THREAD

**Issue by qjasn** [FEX-Emu/FEX#3897]
Environment: Android Busybox Chroot Ubuntu 22.04
CPU: Snapdragon 8 gen 3
Rootfs： ArchLinux

I build fex-emu and don't use the ppa
But Steam can't start.

Output:
steam@localhost:~$ FEXBash steam
steam.sh[29136]: Running Steam on arch rolling 64-bit
steam.sh[29136]: STEAM_RUNTIME is enabled automatically
setup.sh[29228]: Steam runtime environment up-to-date!
/home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[29244]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[29136]: Can't find 'steam-runtime-check-requirements', continuing anyway
tid(29282) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
07/26 20:15:20 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(29282)
07/26 20:15:20 Failed writing minidump, nothing to upload.
src/tier0/threadtools.cpp (2036) : Assertion Failed: semaphore creation failed Invalid argument
src/tier0/threadtools.cpp (2036) : Assertion Failed: semaphore creation failed Invalid argument
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (2439) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (1866) : Thread synchronization object is unuseable
src/tier0/threadtools.cpp (1866) : Thread synchronization object is unuseable

**Comment by Sonicadvance1** [comment]
This is due to running on Android which FEX doesn't support. It is hitting a syscall that isn't supported on Android (this causes the ENOSYS error that `Function not implemented` is causing).

Nothing on the FEX side to do here.
