### ISSUE TITLE
FEXRootFSFetcher does not work in a docker image build step.

### ISSUE THREAD

**Issue by Witixin1512** [FEX-Emu/FEX#3987]
Currently, I am unable to run `yes 1 | FEXRootFSFetcher` within a docker build step, as the output is not a TTY. In such a case, the tool attempts to open a graphical interface and fails to run.

A possible fix would be introducing an environment variable or argument to the program to force it to run in terminal mode.

**Comment by Sonicadvance1** [comment]
Until a specific command line option exists to force the terminal mode, I might recommend the `-y` option. Unless we're missing something for that.

**Comment by Witixin1512** [comment]
I want to say that for my usecase `yes 1` is what I need, as otherwise the prompt to extract the squashfs file goes unanswered.
I'm not too well versed in the internals of the tool to be able to tell if `-y` should make that choice for you or not.

**Comment by Sonicadvance1** [comment]
> I want to say that for my usecase `yes 1` is what I need, as otherwise the prompt to extract the squashfs file goes unanswered. I'm not too well versed in the internals of the tool to be able to tell if `-y` should make that choice for you or not.

You might want the `-x` option in addition then

**Comment by Sonicadvance1** [comment]
A UI path can now be forced with the `--force-ui`option
