### ISSUE TITLE
Couldn't download rootfs list from the server.

### ISSUE THREAD

**Issue by themg95** [FEX-Emu/FEX#4087]
I'm trying to use FEXRootFSFetcher but I'm getting this error:

```
Using default interface naming scheme 'v255'.
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: configure event loop: 0.00027375 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: drm device: 0.0185686 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: connect display: 1.7583e-05 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: client create: 1.3125e-05 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: display implementation: 4.708e-06 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: spawn xwayland: 0.000207125 seconds
Couldn't download rootfs list from the server. Try again in a minute or report on the fex-emu issue tracker.
"FEXRootFSFetcher" process exited with status code: 255
FATAL <sommelier.cc:2960> sl_handle_x_connection_event: got error or hangup (mask 5) on X connection, exiting
```

**Comment by Sonicadvance1** [comment]
Sounds like curl in your setup isn't able to fetch the json from our webserver at https://rootfs.fex-emu.gg/RootFS_links.json

We just execute `curl https://rootfs.fex-emu.gg/RootFS_links.json` and read stdout. So if your system can't access that link then it's a network problem on your end.
Until we convert FEXRootFSFetcher to use libcurl it's a bit harder to show whatever error curl is outputting.

**Comment by themg95** [comment]
just tested the command on its own and it works fine

**Comment by Sonicadvance1** [comment]
Very quirky, maybe it's an issue with interacting with krun.

**Comment by themg95** [comment]
yup just tried `krun curl https://rootfs.fex-emu.gg/RootFS_links.json` and it errors. i'll report it to krun then, ty
