### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jonathf** [FEX-Emu/FEX#4115]
I am on Asahi Linux (Fedora) and following the [installation guide](https://wiki.fex-emu.com/index.php/Development:Setting_up_FEX). During build configuration I get the following error message:
```
CMake Error at Source/Tools/CMakeLists.txt:7 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```
I am at current HEAD 389ad737 and I've installed all the Fedora dependencies.

**Comment by Sonicadvance1** [comment]
Looks like the fedora build dependencies were out of date on the wiki. I believe it just needs the following additional dependencies:
- qt5-qtdeclarative-devel
- qt5-qtquickcontrols
- qt5-qtquickcontrols2

**Comment by jonathf** [comment]
Thanks, that did the trick.
