### ISSUE TITLE
Failed to load driver: vc4 (Raspberry Pi 5)

### ISSUE THREAD

**Issue by Quarek** [FEX-Emu/FEX#4133]
Hi,

I'm running FEX 2410 on a Raspberry Pi 5 with Raspberry Pi OS Lite using the preconfigured Ubuntu 24.04 as RootFS. I've been getting this error when running x86_64 Carla :

```
Carla 2.5.9 started, status:
  Python version: 3.12.3
  Qt version:     5.15.13
  PyQt version:   5.15.10
  Binary dir:     /opt/carla-2.5.9-x86_64/lib/carla
  Resources dir:  /opt/carla-2.5.9-x86_64/share/carla/resources
did not find extension DRI_IMAGE_DRIVER version 1
did not find extension DRI_Mesa version 1
failed to load driver: vc4
did not find extension DRI_Mesa version 1
failed to load driver: vc4
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Frontend pixel ratio is 1.0
libjack.so.0 loaded successfully!
```

Some plugins I'm using with Carla need some video acceleration to run properly, I'm guessing it has to do with the "failed to load driver" part (though I have no way to compare). I've done some digging on Linux video drivers, but this goes beyond my abilities since there's no vc4 drivers available that I could install on the RootFS.

I've been playing around with this for some time, is this known behavior I never noticed, did something change, or am I looking at the wrong thing ?

**Comment by Sonicadvance1** [comment]
Interesting that it isn't finding the driver on your device. Could be the version of mesa that I shipped in that image has broken pi drivers. I tested it locally on my snapdragon device and it seems to be working here at least.

**Comment by Quarek** [comment]
Thank you for your reply,

Do you have an older image I can try ? If not, is compiling/installing a previous mesa release the only option ?

I just checked, and mesa drivers are version 23.3.1-1 on the host and 24.0.9-0 on the RootFS.

**Comment by Quarek** [comment]
Apologies, I should've digged deeper.

One of my scripts upgraded libosmesa6 at some point, which upgraded libgl1-mesa-dri to 24.0.9-0, which caused the issue. Version 24.0.5-1 (as shipped with the image) works perfectly fine.
