### ISSUE TITLE
Half-Life 2: e53f3969e9cc causes hitching under certain `fps_max` conditions

### ISSUE THREAD

**Issue by chadmed** [FEX-Emu/FEX#4196]
**What Game**
[Half-Life 2](https://store.steampowered.com/app/220)

**Describe the bug**
Half-Life 2 suffers from extreme hitching and instability - even at menus - on Apple Silicon machines. Notably, this _only_ occurs when the engine is actively limiting frames via `fps_max`. It does not occur when `fps_max 0`, nor does it occur when the achievable framerate is lower than the `fps_max` limit. Of course, this is is almost never the case on these machines ;)

This is most obvious in certain menu maps, as well as while playing. I have bisected this down to e53f3969e9cc. Reverting back to the old `pause` behaviour clears this issue.

**To Reproduce**
1. Fire up Half-Life 2
2. Go to Episode 2
3. Observe the menu system hitching
4. Fire up an Episode 2 save game
5. Observe the game hitching to the point of unplayability

**Expected behavior**
The game should run without hitching.

**System information:**
 - OS: Gentoo Linux
 - CPU/SoC: Apple M2 Max (also repros on M2, M2 Pro, and M1 Pro)
 - Video driver version: [Mesa `asahi-20241204`](https://gitlab.freedesktop.org/asahi/mesa/-/tags/asahi-20241204)
 - RootFS used: @WhatAmISupposedToPutHere/fex-rootfs (Minimal Gentoo x86 with asahi mesa overlayed)
 - FEX version: Prints nothing (???), but it's upstream FEX-2410 with no patches.
 - Thunks Enabled: Yes

**Additional context**
 - Is this an x86 or x86-64 game: x86
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: Untested
 - Is this a Vulkan game: Via Source's DXVK integration
   - If Yes, What is your Vulkan driver: Honeykrisp. Behaviour is reproducible with both the DXVK and toGL pipelines.

**Comment by Sonicadvance1** [comment]
WFE change sounds like a red-herring, Apple Silicon wfe implementation averages 36cycle sleep time, so 1,500 ns average but frequently drops to 0 cycles. Intel does around 141 cycles per pause instruction on their hardware, which should be around 56ns to 94ns depending on CPU.

These are tiny numbers.

**Comment by chadmed** [comment]
Could be, but doing nothing to FEX-2412 other than reverting e53f3969e9cc definitely does fix hl2.

**Comment by asahilina** [comment]
WFE requires doing a SEV on another CPU, it's intended to be used in spinlocks and such. If you don't do a SEV somewhere related, WFE could effectively wait forever (in practice, until some other software/kernel does a SEV, but that's not something you control). If you are seeing "consistent" WFE wait times that means you *do* have other software doing enough SEVs, but that's just a coincidence then.

**Comment by jannau** [comment]
Testing `wfe` with the google-benchmark from the linked rust commits yields:
```
--------------------------------------------------------------
Benchmark                    Time             CPU   Iterations
--------------------------------------------------------------
BM_scalar_increment      0.286 ns        0.286 ns   2446395414
BM_yield                 0.286 ns        0.286 ns   2446636789
BM_isb                    8.60 ns         8.59 ns     81608626
BM_wfe                   60155 ns        59987 ns         9937
```
on a M2 Pro. So with a average time of around 60 ms it's no surprise that this breaks if it's use for idling to avoid exceeding 60 fps.
Timing of `wfe` entirely unpredictable and depends on what else is going on the system. I don't think it's a good idea to use it for unconditional and predictable a short waits.

```
#include <benchmark/benchmark.h>

static void BM_scalar_increment(benchmark::State& state) {
  int i = 0;
  for (auto _ : state)
    benchmark::DoNotOptimize(i++);
}
BENCHMARK(BM_scalar_increment);
static void BM_yield(benchmark::State& state) {
  for (auto _ : state)
    asm volatile("yield"::);
}
BENCHMARK(BM_yield);
static void BM_isb(benchmark::State& state) {
  for (auto _ : state)
    asm volatile("isb"::);
}
BENCHMARK(BM_isb);
static void BM_wfe(benchmark::State& state) {
  for (auto _ : state)
    asm volatile("wfe"::);
}
BENCHMARK(BM_wfe);

BENCHMARK_MAIN();
```

**Comment by asahilina** [comment]
That's 60us, but still, as far as I know it's unbounded if nothing else does a `sev`.

**Comment by mzyngier** [comment]
Drive-by comment:

> WFE requires doing a SEV on another CPU, it's intended to be used in spinlocks and such. 

Not necessarily. The clearing of the exclusive monitor, the event stream from the arch timer, or an interrupt will do just as well. Which is why there is no SEV in Linux's spinlock implementation, only a SEVL to bypass the first WFE, and we rely on the clearing of the monitor from another CPU to exit WFE.

Gory details in rule `R_KBMFC` in the ARM ARM.

If you need this to be *time bound*, WFET could be the tool for the job, but the Apple HW doesn't implement it.

**Comment by asahilina** [comment]
> Drive-by comment:
> 
> > WFE requires doing a SEV on another CPU, it's intended to be used in spinlocks and such.
> 
> Not necessarily. The clearing of the exclusive monitor, the event stream from the arch timer, or an interrupt will do just as well. Which is why there is no SEV in Linux's spinlock implementation, only a SEVL to bypass the first WFE, and we rely on the clearing of the monitor from another CPU to exit WFE.

Sure, but those are all explicit events, while x86 `pause` isn't supposed to wait for anything, it's just a hint.

> If you need this to be _time bound_, WFET could be the tool for the job, but the Apple HW doesn't implement it.

I don't think we could determine an "appropriate" time interval... what `pause` is supposed to do is hint to avoid memory ordering pathological behavior during spin-loops I think? So I think you'd have to look at an actual spinlock implementation on x86, how it is translated by FEX (in different TSO modes), and then decide whether something helpful can be done on ARM in that context.

**Comment by mzyngier** [comment]
> So I think you'd have to look at an actual spinlock implementation on x86, how it is translated by FEX (in different TSO modes), and then decide whether something helpful can be done on ARM in that context.

Can't agree more. It'd probably make sense to have a load exclusive of the lock word just before hitting WFE, which then would give the proper event semantics. But that's assuming the code translation engine can work out what that lock word is, and that's quite a leap of faith.
