### ISSUE TITLE
Investigate available jits

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#46]
javascript/wasm side
- [ ] v8
- [ ] Mozilla

.net side
- [ ] dotnetcore
- [ ] mono

Others?

**Comment by skmp** [comment]
I have dotnetcore installed and the hosting samples working. It doesn't have a C++ level codegen api.
I also have mono installed and the samples working. It has a very minimal C++ level codegen api.

Both have full-ish codegen apis from the C# side.

I'll be building v8 today to checkout the wasm AOT(s) and JIT(s).
wasm's dynamic module loading is a bit weak, but that might not be a blocker

binaryen is also a fun project for the wasm side

**Comment by Sonicadvance1** [comment]
These have been investigated.
Not worth pulling in any of them.
