### ISSUE TITLE
Parse ELF interpreter correctly so we don't have to pass in dynamic linker

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#49]
Right now ELFLoader is not pulling in the dynamic linker from the ELF.
This is requiring us to launch apps through the linker directly, which clang absolutely hates.
Pass it through ELFLoader so we no longer need to do this.
Saves us headaches, will be needed when we hook through binutils.

**Comment by skmp** [comment]
Yes please can we have this
