### ISSUE TITLE
glibc SSSE3 strcmp returning invalid results on 32bit

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#514]
Haven't fully investigated why this fails, it's a huge function.

**Comment by Sonicadvance1** [comment]
```#include <cstring>
#include <cstdio>
#include <unistd.h>
#include <cstdlib>
#include <mutex>
#include <stdarg.h>
#include <sys/stat.h>

__attribute__((noinline)) int cmp(const char *input, const char *str) {
  return strcmp(input, str);
}

int main(int argc, char **argv) {
  char *text = (char*)malloc(0x4000);
  const char str[] = "This is a test string-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\0";
  write(0, str, strlen(str));
  int res = cmp("This is a test string-", str);
  snprintf(text, 256, "Returned: %d\n", res);
  write(0, text, strlen(text));
  return 0;
}
```
Random test app I had to testing this.

**Comment by Sonicadvance1** [comment]
Tossing over to phire

**Comment by skmp** [comment]
I had to fix several bugs in OpDisp / RIP 32 bit handling around this, and after that it seems to work just fine. Any specific compiler/glibc version that needs to be checked?

**Comment by Sonicadvance1** [comment]
I believe I tested with glibc 2.31 or 2.32

**Comment by Sonicadvance1** [comment]
Application that reproduces. Needs no arguments, just run native versus FEX.
[strcmp.zip](https://github.com/FEX-Emu/FEX/files/6027318/strcmp.zip)

**Comment by Sonicadvance1** [comment]
Okay, the return results here are due to SSSE3 usage versus newer SSE4.x usage.
We match qemu behaviour here. Results will change once we support new SSE versions just like on physical x86 hardware.
