### ISSUE TITLE
Execve fails due to /proc/self/exe usage

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#571]
We determine if we are in "Interpreter" mode by checking application executable name to be FEXInterpreter.
Interpreter mode is necessary since we need to ignore arguments passed in since it breaks execution in a lot of cases.

`/proc/self/exe` sees through our softlink to FEXLoader which means we lose the determination that we are the interpreter.

We have two options.
- Disable all argument loading and just use FEXConfig for option setting.
- Do a hardlink install to FEXLoader

**Comment by Sonicadvance1** [comment]
I'm in favour of hard link, argument setting is super useful.

**Comment by skmp** [comment]
In favor of hard link here as well
