### ISSUE TITLE
Add support for SSE 4.2

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#574]
Only something to worry about once our performance is good enough for newer AAA titles.

Apparently Doom Eternal uses the CRC instruction specifically.
The string compare ops likely won't map very well to anything in AArch64...

**Comment by Sonicadvance1** [comment]
Control Ultimate Edition also relies on SSE 4.2

**Comment by Sonicadvance1** [comment]
Horizon Zero Dawn uses CRC32 at the very least.

**Comment by Sonicadvance1** [comment]
CRC32 implemented with #1541 which gets Horizon Zero dawn running.

**Comment by skmp** [comment]
@lioncash I think this is done at this point?

**Comment by Sonicadvance1** [comment]
It's not, the string comparison ops aren't implemented.

**Comment by Sonicadvance1** [comment]
Interestingly, Control checks for SSE 4.2 via CPUID, but we can't even test force enabling it since utility libraries will use SSE4.2 string instructions if exposed.

Control early bails out if CPUID doesn't claim to be available.

**Comment by lioncash** [comment]
Currently PCMPISTRI, PCMPESTRI, and PCMPISTRM are supported (or pending):

https://github.com/FEX-Emu/FEX/pull/2632 - Adds support for PCMPESTRI/VPCMPESTRI
https://github.com/FEX-Emu/FEX/pull/2649 - Adds support for PCMPISTRI/VPCMPISTRI
https://github.com/FEX-Emu/FEX/pull/2677 - Adds support for PCMPISTRM/VPCMPISTRM

all that remains to be implemented is PCMPESTRM/VPCMPESTRM
