### ISSUE TITLE
Support AVX list

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#581]
Find a list of games that use AVX unconditionally to gauge priority for implementing.
We need both good enough performance and a list of games that use AVX before thinking about implementing.
It'll have a minor perf hit to implement since all of our context switching ends up being twice the size.

Games that use AVX unconditionally (at time of writing or that we've discovered):
- Cyberpunk 2077 (Unconditional usage removed in 1.05)
- Metro Exodus (And enhanced edition)
- Sonic Frontiers
- Uncharted: Legacy of Thieves Collection
- Returnal
- Death Stranding
- Forspoken
- Star citizen
- Sea of Stars
- Starfield

https://wiki.fex-emu.com/index.php/Category:AVX_CPU_Feature

**Comment by Sonicadvance1** [comment]
Death Stranding also uses AVX unconditionally.

**Comment by lioncash** [comment]
AVX1 support is in place as of writing. Now all that remains is the gather instructions from AVX2 and then CPUID support for that can be put in place

**Comment by Joshua-Ashton** [comment]
Helldivers 2 needs AVX

**Comment by alyssarosenzweig** [comment]
🎉
