### ISSUE TITLE
Add optimization pass that changes integer divide to shifts

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#586]
Loads of integer divides are dividing by powers of two.

First task is to investigate how often the divisor can be const propagated.
Second task is to see what percentage of those divisors are power of twos
Third task is to convert the division from a divide to a shift. Either by using SBFE or BFE for the sign handling depending on udiv or sdiv.

**Comment by alyssarosenzweig** [comment]
I'm unconvinced this is appropriate. If it is, motivate with instcountci hot blocks.

**Comment by Sonicadvance1** [comment]
Sounds reasonable to close, we already convert large divides when possible, and compilers go to the ends of the earth to delete integer divides on x86, so it's unlikely that we'll see const-prop capable divides that can be turned in to shifts.
