### ISSUE TITLE
DEQP unit tests runner doesn't run correctly under FEX

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#602]
When trying to run the unit test runner it will just try running some WGL tests and stop early.
https://android.googlesource.com/platform/external/deqp/
Follow build steps in external/openglcts/README.md for building
then run the output `cts-runner` or `glcts` program
Not sure what is wrong here but these would be nice to get running.

**Comment by alyssarosenzweig** [comment]
works for me
