### ISSUE TITLE
Investigate gvisor test failures

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#620]
## Overview
Several gvisor tests fail, and those are largely real failures

- [ ] Investigate failures
- [ ] Create tickets

## Follow up
- [ ] Solve tickets

**Comment by phire** [comment]
Investigated and opened #753 for the following gvisor tests:

 * memfd_test.jit.gvisor
 * proc_test.jit.gvisor
 * socket_abstract_test.jit.gvisor
 * socket_filesystem_test.jit.gvisor
 * socket_unix_pair_test.jit.gvisor

**Comment by Sonicadvance1** [comment]
These were investigated and documented in the unittests file.
