### ISSUE TITLE
Get SMC working with a memory watcher

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#681]
Would be nice to use Soft dirty PTE for this, but the interface isn't something we can use.
Full userspace tracking with mirror support until soft dirty PTE gets wired correctly.

**Comment by skmp** [comment]
Leaving notes here: Current work in #1558, more documentation in #1639 #1638

**Comment by skmp** [comment]
Largely implemented in #1558, there are follow up tickets there for remaining work.
