### ISSUE TITLE
Investigate: intermittent crash in Geekbench 4's llvm benchmark

### ISSUE THREAD

**Issue by phire** [FEX-Emu/FEX#771]
This might be related to the multithreading issues, but I'm creating this issue to remind me to check later after multithreadding (#680) and reclusive terminate bugs are fixed. 

Also after #683

``` 
$ Bin/FEXLoader -s  -T 8  -- ../../Geekbench-4.4.4-Linux/geekbench_x86_64 --section 2  --workload 212
Geekbench 4.4.4 Pro : http://www.geekbench.com/

terminate called recursively
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by phire** [comment]
BTW, I was only able to get this reproducible in the (then) current version of FEX by inserting a sleep or busy loop before the futex syscall.

**Comment by skmp** [comment]
clang now works reliably after #790 #823 & #825, and we're able to build fex under fex. Is this still an issue?

**Comment by phire** [comment]
Currently testing, but it's looking like this is fixed.

**Comment by phire** [comment]
This appears to be fixed.
