### ISSUE TITLE
GDBServer: Crashes due to initialisation order issue.

### ISSUE THREAD

**Issue by phire** [FEX-Emu/FEX#777]
Currently crashes if `FEXCore::Config::SetConfig(CTX, FEXCore::Config::CONFIG_GDBSERVER, ...)` is called before `FEXCore::Context::SetSignalDelegator()`

Probably need to delay initialisation of the GdbServer until `InitCore()` is called.

**Comment by Sonicadvance1** [comment]
Confirmed. This is now fixed with my reordering of initialization.
