### ISSUE TITLE
Deal with Robust list handling

### ISSUE THREAD

**Issue by phire** [FEX-Emu/FEX#802]
For x86_64, the guest glibc's set_robust_list syscall just overrides the host glibc robust list. Which might be fine if fex itself never needs robust futexs.

But this gets iffy with thunks and libraries.

For x86_32, we just discard the guest robust list, which is problematic.

**Comment by Amanieu** [comment]
I've honestly never seen any code which actually relied on robust mutexes working to function. I don't expect this to be a problem in practice.

For x86_32, you can only do this reliably if you have kernel support for compat syscalls. The kernel actually has 2 `robust_list_head`s for each thread: a normal one and a compat one. So you can keep using the normal one for FEX while using the compat one for the translated process.

**Comment by phire** [comment]
superseded by #809
