### ISSUE TITLE
Thunks are broken?

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#804]
I can't get thunks working on an AArch64 host.
We need a guide on how to get these to work.
Tried installing to the precompiled rootfs (Just overwrite a bunch of the libraries with the same versioned libraries?) and it just tried calling some thunked function (that didn't exist as a hash?) and explodes.
This is completely blocking for anyone wanting to toy with thunks.

See the discussion on Discord, even me throwing an hour or two of time at the problem, couldn't figure out why things weren't working.

**Comment by skmp** [comment]
I just did a quick test on x86-64 and it works, as soon as I have access to aarch64 i'll test that as well.

**Comment by skmp** [comment]
Can't repro here.

Build fex via
- Latest main
- CC=clang CXX=clang++ cmake .. -G Ninja
- Configured: Debug, Assertations, Thunks
- ninja FEXLoader host-libs guest-libs

Build ubuntu 20.04-1 rootfs via (to match lsb_release -a on my host)
- cd ~/rootfs
- wget http://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-base-20.04.1-base-amd64.tar.gz
- mkdir 20.04
- cd 20.04
- tar -xf ../ubuntu-base-20.04.1-base-amd64.tar.gz
- sudo mount -o /dev dev
- sudo mount -o /tmp tmp
- cp /usr/bin/qemu-x86_64-static usr/bin/
- sudo chroot .
- > echo nameserver 8.8.8.8 > /etc/resolv.conf
- apt update
- apt install mesa-utils
- exit

Then launched GLX gears via
- cd ~/projects/FEX/build
- Bin/FEXLoader -R ~/rootfs/20.04 -t Host -- ~/rootfs/20.04/usr/bin/glxgears

It worked just fine.

This is on the Lenovo C630

**Comment by nsklaus** [comment]
these instructions here, are what is missing on the github readme.md or wiki section of this project.
thanks @skmp

**Comment by Sonicadvance1** [comment]
Confirmed thunks are working, just need to write documentation now.
