### ISSUE TITLE
x87: Implement FTW

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#871]
FTW doesn't even exist on the context. We always write as zero atm, and never read.

**Comment by Sonicadvance1** [comment]
This is partially implemented now.
Mostly this is fairly pricey to implement, so we only support Empty, valid, and Zero (on examine).
The FTW becomes valid on value push, and empty on value pop.
This bare minimum implementation was written for a wine application that was pushing valid x87 tags until it came up empty.

**Comment by alyssarosenzweig** [comment]
i think this can be closed
