### ISSUE TITLE
Factorio 1.1.30 crashes when loading

### ISSUE THREAD

**Issue by Hacker1245** [FEX-Emu/FEX#957]
Factorio is crashing at around 95% when loading sounds, attaching a log file from Factorio. 
I'm running FEX on a VirtualBox x64 VM running Ubuntu 20.04. 
Used the newest FEX version at the time of writing this. 
Factorio was downloaded from the game's website.
Chroot is also a base Ubuntu 20.04 rootfs with installed packages from the wiki. 
Did not remove the specified files and folders as that causes a crash right at the start with some memory crash, attaching what I got out of GDB then.
[factorio-current.log](https://github.com/FEX-Emu/FEX/files/6260367/factorio-current.log)
![clipboard](https://user-images.githubusercontent.com/29224894/113620272-63c4d880-965a-11eb-88a0-08d37783a833.png)

**Comment by Sonicadvance1** [comment]
Confirmed this issue here.
Looks like it is a bug in the x86 JIT core, runs fine on AArch64 here.
Seemingly a change from the 1.0.0 version I had on GOG versus the 1.1.30 version from their website.
Triaging...

**Comment by Sonicadvance1** [comment]
Thanks for the bug report. #958 will fix it for you.

**Comment by Sonicadvance1** [comment]
Additional information for this. I have updated the wiki to remove the information about the absolute path with ld-linux.so. That is no longer necessary when setting up a rootfs.
